### PR TITLE
Create dv_questions.txt

### PR DESCRIPTION
**Pull request by Sofwath**
Dhivehi (dv) - questions

### CODE REVIEW

**Comment by Gregoor** [comment]
Looks much better, thanks :) Have the sentences been reviewed and are they CC0?

**Comment by Sofwath** [comment]
yes. they have been reviewed and are from public domain sources.

**Comment by Gregoor** [comment]
Great!

**Comment by peiying2** [comment]
I will let @Sofwath answer here. From his email communication, it should be. Sofwath, this is what CC0 referring to: https://creativecommons.org/publicdomain/zero/1.0/

**Comment by Sofwath** [comment]
yes, from the email communications with @peiying2  this was made clear.

**Pull request merged**
