### PR TITLE
respond function for server responses

### PR DESCRIPTION
**Pull request by Omniscimus**
Made a class which can be used to send server responses. This fixes the XML errors in the Firefox console (#397). The cause of these errors was that the Content-Type header wasn't being set. The Responder class specifies some defaults. For example, if the Content-Type is not set, it uses `text/plain`. Using this class should prevent similar issues in the future.

### CODE REVIEW

**Comment by mikehenrty** [comment]
@Omniscimus First of all, this is really nice code! And thank you for taking this on.

That said, I think we need to rethink this approach. First, we are allocating new objects for every request, which causes work for the garbage collector at the end of the day, and in a high request enviroment I could see this slowing down the app somewhat.

More generally though, I think a good approach would be to use a library to handle our static requests. Initially we were using [node-static](https://www.npmjs.com/package/node-static), but we took that out because we were having issues with static requests. It turns out, this was not related to node static. So i think the best approach would be to use a library rather than building out a fully featured static backend. What do you think @Omniscimus ?

**Comment by Omniscimus** [comment]
@mikehenrty Ah, I hadn't thought of garbage collection.

Todo:
- use node-static instead of static.ts (revert  be2789adfec2310a4487b45927be81bb8bf5c5bd)
- use some kind of function instead of the Responder class to generalize non-static server responses

**Comment by Omniscimus** [comment]
@mikehenrty How about this? Everything seemed to work on my localhost, but maybe I overlooked something.

**Comment by mikehenrty** [comment]
Sorry about the delay here, this looks good! 👍

**Pull request merged**
