### PR TITLE
Add Open Voice Challenge Terms & Conditions

### PR DESCRIPTION
**Pull request by rileyjshaw**
Test plan:

- Navigate to localhost:9000/en/?challenge=pilot&team=mozilla
- Click "challenge terms" or "Terms & Conditions"

Common Voice Open Voice Challenge Legal Terms should appear (once
STOPSHIP is resolved)

Note: before merging this to `master`, we must ensure the corresponding
legal document exists in our `mozilla/legal-docs` repository as noted in
the `STOPSHIP` comment.

### CODE REVIEW

**Comment by rileyjshaw** [comment]
All STOPSHIPs have been resolved. This PR is now good to go.

**Comment by phirework** [comment]
So clicking on either of the links sends me to http://localhost:9000/en/challenge-terms, which is a 404. Looking at the `fetchLegalDocument` function, it seems like it's expecting http://localhost:9000/challenge-terms/en.html, which I've confirmed does work.

**Comment by rileyjshaw** [comment]
Thanks @phirework! I missed some wiring for the "pretty" route – it should be hooked up now :)

Note, the unstyled page is available for all documents, eg. https://voice.allizom.org/terms/en.html.

**Comment by phirework** [comment]
Looks great!

**Pull request merged**
