### PR TITLE
New sentences for Common Voice.

### PR DESCRIPTION
**Pull request by janetcshih**

### CODE REVIEW

**Comment by mbebenita** [comment]
Thanks. Can you provide some details as to where you got these sentences?

**Comment by mikehenrty** [comment]
YESH!!!

**Comment by mikehenrty** [comment]
> Can you provide some details as to where you got these sentences?

This is from War of the Worlds too, I asked her to help out.

**Comment by mbebenita** [comment]
Ah okay, great, thanks.

**Pull request merged**
