### PR TITLE
Dhivehi - dv

### PR DESCRIPTION
**Pull request by Sofwath**

### CODE REVIEW

**Comment by Gregoor** [comment]
Heya, thanks for the PR! Something went wrong with the PR, as it contains many non-relevant commits. Maybe rebasing it onto master would solve this? (not entirely sure what went wrong tbh)

**Comment by peiying2** [comment]
Agreed. Let's close this one and try again.

@Sofwath let's try again. If you are not sure, you send me the file and I will see if I can help you set up the folder and attach one file. You can add the rest whenever you are ready.

**Comment by peiying2** [comment]
Looks like the attempt is replaced with this one #1754. Close this one then.

**Comment by Gregoor** [comment]
Thanks Peiying!

**Pull request closed without merging**
