### PR TITLE
[fr] add French sentences from Le Comte De Monte Cristo tome 1 (public domain)

### PR DESCRIPTION
**Pull request by nicolaspanel**
Sentences were extracted from https://www.atramenta.net/lire/le-comte-de-monte-cristo-tome-i/6318 (epub)

More to come if you are interested

NB: some lines may be a little bit long...

### CODE REVIEW

**Comment by lissyx** [comment]
@nicolaspanel Thanks, but I'm pretty sure some Monte Cristo sentences were pushed from Gutenberg

**Comment by lissyx** [comment]
Actually should be okay, no matching id http://www.gutenberg.org/ebooks/17989 http://www.gutenberg.org/ebooks/17990 or http://www.gutenberg.org/ebooks/17991

**Comment by lissyx** [comment]
@mikehenrty Should be okay to merge. This should also help balance the dataset wrt addresses.

**Comment by mikehenrty** [comment]
> NB: some lines may be a little bit long...

Yeah, I agree with this. We should aim for sentences that take ~5 seconds to speak, which we've estimated to be 10-15 words. Some of these sentences are ~30 words. Can we trim all the sentences above 15 words?

**Comment by nicolaspanel** [comment]
I suggest to filter them instead.

**Comment by ronane** [comment]
To me, it seems more relevant to filter them too. A trimmed sentence could have no sense and destabilize the reader or the end could have been pronounced differently if the sentence would have been complete.

**Comment by Gregoor** [comment]
Thanks for your efforts! We're about to launch a beta of our sentence collection tool, please submit your sentence through that once it's ready. It'll be announced in our Discourse very soon:
https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530/

**Pull request closed without merging**
