### PR TITLE
Inzan n teqbaylit - Kabyle proverbs

### PR DESCRIPTION
**Pull request by anzart**
Please add your Kabyle proverbs!

### CODE REVIEW

**Comment by anzart** [comment]
Hi @mikehenrty ! They are popular proverbs from Kabylia collected on the web.

**Comment by belkacem77** [comment]
Hi @anzart 
Thanks for work.
Please, some these proverbs are already added to common Voice.
To avoid dupplication and for a second check, we are using a Gihthub repo where the kab team is talking and sharing corpora.

Please would you like add them here https://github.com/belkacem77/tuddar, we will check them together and delete sentences we already added to Common Voice. 

@mikehenrty Proverbs are part of our popular litterature as wel as idiomatic expressions, popular tales, popular poetry,....

**Comment by belkacem77** [comment]
@anzart also, person names should be re-wrote like Lounis Aît Menguellet->Lunis At Mengellat

There is some other checks we should make. Please push them here first:  https://github.com/belkacem77/tuddar

**Comment by anzart** [comment]
Azul @belkacem77 , I just pushed the "kabyle proverbs" file into the"./tuddar/commonvoice/" folder.

**Comment by belkacem77** [comment]
Azul @anzart 
I merged it. Most of them are already exposed on Common Voice. You can send your sentences on our repo. After correction, we will expose them on Common Voice.

Please don't forget to add the source of your sentences. 
We need verb flexions, so you can use the Website of Phd Zerrad and combine them with some names, preposition, adverbs ... described witin the kabyle grammar of the same author to build sentences from scratch.

There is also, some other ressources from where we can build sentences: Publications of Phd Moussa Imarazène, Phd Kamel Bouamara, Phd Mohand Akli Sahli... from the DLCAs Departments, we can use them to cover all verb and noun flexions, the diffrent pronoun, preporisiont forms....

We also need a corpus about named entities but used within sentences (places names, known persons, organizations, countirs, languages,....)

Thanks for your help.

**Comment by anzart** [comment]
Azul @belkacem77 ,
I would do my best to collect these sentences, so I'm on a project to translate all the voice assistant commands ( Google Assistant, Alexa d'amazon..etc) into Kabyle to add them on Common voice.

**Comment by belkacem77** [comment]
Azul @anzart 
Thanks for help.$
Yeah we still looking for more sentences to expose them on Common Voice. So, we should work outside Common Voice to check and correct all sentences and also to avoid dupplication because we have no mean to do that. So I told to the team to send all sentences on our own repository to correct them and check if they are not dupplicated. I'm using a locale database.
You can also connect with us on FB (https://web.facebook.com/mouhouslimane.naithbelqacem). We have social pages where we are talking about everything (corpus, sources, tutorials, training sessions.....)...  The team is growing, please connect with us on FB and VK to know more about the team and how we are working to gather sentences.

**Comment by mikehenrty** [comment]
Is this PR still valid? Or will we use @belkacem77's repository to submit the new sentences?

**Comment by belkacem77** [comment]
@anzart please close this PR. I checkec the proverbs. I'll just keep some as most of them are already exposed on Common Voice.

**Pull request closed without merging**
