### PR TITLE
Add German sentences by est31

### PR DESCRIPTION
**Pull request by est31**

### CODE REVIEW

**Comment by est31** [comment]
200 sentences from me. Mostly I've (roughly) translated them from my already present english contribution. There are some left out sentences though, as well as added ones.

**Comment by mikehenrty** [comment]
@Djfe @MichaelKohler, any chance you could have a quick read through of these?

**Comment by est31** [comment]
Thanks for the quick review, @jf99 ! And also thanks for bootstrapping the german corpus. Really great work :).

**Comment by mikehenrty** [comment]
thanks @jf99! (weren't you supposed to be taking a break??) great work both!

**Pull request merged**
