### PR TITLE
Upgrade to fluent 0.8 and fluent-react 0.8

### PR DESCRIPTION
**Pull request by stasm**
This is a WIP. I haven't been able to run `voice-web` locally so I haven't had a chance to test this PR. I've tried using both docker-compose and setting up the environment locally, but to no avail :(

I'm submitting this PR to put this upgrade on you radar, and to see what CI thinks of it.

### CODE REVIEW

**Comment by stasm** [comment]
@Gregoor Can you help me test this locally please?

**Comment by Gregoor** [comment]
Sorry that both methods of running it locally didn't work out. If you have easy access to the error logs (if there were any), would you mind opening issue(s) for it?

RE this PR, I ran it locally and it worked mui bien, thank you! 🙂 I think this is ready to be merged, but I'll wait for your go @stasm!

**Comment by stasm** [comment]
Thanks, @Gregoor! I'm back from vacation today. Would you like me to work on resolving the conflicts in this PR?

**Comment by Gregoor** [comment]
Welcome back! Hope you had a good vacation 🙂 I can also resolve them while merging, if it's ready to go from our side.

**Comment by Gregoor** [comment]
Merged! Also made the renames you were afraid of (TypeScript makes me unafraid 😁). Thanks for keeping us up to date!

**Comment by stasm** [comment]
Yay, great news. Thank you for your help, @Gregoor!

**Pull request merged**
