### PR TITLE
Add link to Sentence Collector to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by davidak**
fixes https://github.com/mozilla/voice-web/issues/1664

### CODE REVIEW

**Comment by Gregoor** [comment]
Thanks! I think we might want to also have the link to the discourse post though. Wdyt @nukeador?

**Comment by mozillakab** [comment]
@Gregoor 
As you said, both links to SC and the discourse post should help

**Comment by davidak** [comment]
Shouldn't it be unnecessary to read the whole post and just have all relevant information in the SC tool, from a UX point of view?

And i think it is. There is a How-To and rules when to accept a sentence. That is still missing in the main common voice tool (the community works on it).

**Comment by stefangrotz** [comment]
This would have been extremly helpfull for me. It took me a few weeks until I found the sentence colector since I only read the readme and only weeks later I looked at the FAQs and Discourse. 

There are a lot of people who only read the readme on github if they want to contribute to a project. I talked to som people who helped in the early phase of the project and they did not know that the sentence collector exists.

**Comment by rileyjshaw** [comment]
Thanks for the contribution @davidak, and sorry for the delay! This was addressed in https://github.com/mozilla/voice-web/pull/2263, so I'm closing this PR.

**Pull request closed without merging**
