### PR TITLE
add all sentences

### PR DESCRIPTION
**Pull request by ftyers**
Here are all the sentences from the Chin group.

### CODE REVIEW

**Comment by Gregoor** [comment]
I'm looking into deploying the changes today, so hopefully yes! Josh told me it would be good to have this merged for your Chin-speaking session 🚀

**Comment by ftyers** [comment]
Yep! :D \o/

**Comment by Gregoor** [comment]
activated Chin and deployed!

**Comment by ftyers** [comment]
Wow, lightning speed! Thanks!!!

**Comment by Gregoor** [comment]
Happy coincidence, but I'll take it 😁 Let me know if there's stats you want for / after the event.

**Pull request merged**
