### PR TITLE
Add Dutch sentences

### PR DESCRIPTION
**Pull request by danielsjf**
Added 2773 Dutch sentences

### CODE REVIEW

**Comment by sroet** [comment]
I will read your sentences during my breaks and will update this comment (some things are differences between BE Dutch and NL Dutch, you don't have to change them):
I read until sentence 60: 

comments:
10: moet eindigen met een vraagteken
19: zoo = dierentuin in ABN geloof ik
21: 'Die = De' (dubbele aanduiding 'die .. van dat...' leest vreemd)
21: gekend = bekend
22: literatuur moet met hoodletter, als het om de naam van de prijs gaat
25: verhuis = verhuizing
35: is onlogisch ('voldoende ruimte voor' of 'voldoende kastruimte door'
37: bevat een afkorting die kan worden uitgesproken als "de koninklijke nederlandse luchtvaartmaatschapij"
38: Oppassen => pas op (leest makelijker, meer spreektaal)
38: langs daar => daarlangs (Vlaams vs NL)
43: 'de' voor belletles is niet nodig
44: 'uitgestorven nu' => 'nu uitgestorven"
53: "Het" is niet nodig
54: ik zou ' na de operatie' naar het einde van de zin verplaatsen
56: 'kop = top' in NL maar vind deze uitdrukking leuker
60: modern => moderne

**Comment by danielsjf** [comment]
@sroet yes I tried to put in both types of Dutch :-) both can be used so should be recognised. I'm Belgian so feel free to add some more specific Dutch expressions/words. The same for the locations. I also used names from the top 50 Dutch names from the last century. They seemed to more or less match the Belgian names (my feeling), but again feel free to add more.

I'll update the sentences when you get a little further!

**Comment by sroet** [comment]
> Actually, I think it is not a bad idea if I just duplicate the sentences where both a Dutch and a Belgian way is possible. In that case we'll have both.

I am also in favour, because in my opinion a training set should include both (as these are not different languages).
 However, I do wonder:  @Djfe what did you guys decided to do about the differences between German/Austrian/Swiss-German? (Sorry if you are not the right person to ping, but you seem really active)

**Comment by sroet** [comment]
@danielsjf  I read through the first 500 sentences, they are really nice to read. Most feedback is about differences between BE/NL, but there are some small mistakes as well ;) 
I will make a new comment for the next 500 sentences.

I don't know if I have the time to read all the sentences, but will try to keep working on them during my breaks. If there are any other Dutch speakers around, I would love some help.

**Comment by danielsjf** [comment]
@sroet Thanks a lot for reading them. I'll probably correct them in the weekend. I actually grew up close to the Dutch border, but it's still funny to see how many small differences remain present :-) Let alone in pronunciation.

**Comment by Djfe** [comment]
I think we only have German standard German (Hochdeutsch) currently
https://en.m.wikipedia.org/wiki/Standard_German

right? @jf99

I can't add anything else because I can't write or speak Austrian, Swiss, Bairisch, etc.

I'm not sure how we will collect the others.
For Austria and Switzerland there will probably be different languages since they are different countries, but I don't know what Mozilla's plan on German dialects is.

**Comment by sroet** [comment]
@Djfe @danielsjf to answer #1000 (to keep discussion relevant)
> (I'm unsure whether Dutch people can pronounce Belgian Dutch right (you might want to ask that over there)

The issue is that the for certain sentences the natural order or natural form of the words is slightly different. So as a NL Dutch speaker I might swap words by misreading (leading to an invalid recording) or feel quite awkward speaking it as it is written (leading to a unnatural recording).
I don't know if this is also true the other way around

**Comment by jf99** [comment]
@Djfe 
> I think we only have German standard German (Hochdeutsch) currently

True for at least 99%, but I tried to include a few regional terms (search for gell, freilich, schnacken).

**Comment by sroet** [comment]
Al right, I found some more time. I will update this comment for senteces 500-1000. Sentences that I know to be a differences are labelled with "(BE/NL)" and sentences that I suspect to be different are labelled with "(BE?/NL)"
I read untill sentence 600:
503: zou "aan de mensen bekend gemaakt" naar achter verplaatsen (en een spatie toevoegen).
507: "omwalling" is oud Nederlands, zou het het hernoemen naar "muur" o.i.d.
508:  "waren typisch in" => "zijn typisch voor"  klinkt logischer voor mij
510:  "landbouwers" => "boeren" (landbouwers mag maar wordt weinig gebruikt in NL)
511: "steekt" => "zit" (BE?/NL)
514: "De" onnodig
514: "in" => "voor"
517: "zowel" moet na "met"
520: is onlogisch, zou omschrijven naar "zij doet een opleiding tot ingenieur"
525: ontbijtgranen .. ontbijt klinkt vreemd, zou er "heb vanmorgen ontbeten met ontbijtgranen" van maken
529: "vieruurtje" is een onbekende term voor mij, NL is denk ik  "tussendoortje"
531: "appelsienen .. appelsiensap" => "sinaasappels ... sinaasappelsap" (BE/NL)
535: "zit" => "staat" ( ik ga er van uit dat het om files (traffic) gaat)
538: "allergisch aan" => "allergisch voor" (BE?/NL)
549: "va" => "van"
551: "koelbloedig" => "koudbloedig" (BE?/NL)
553: "even passeren" wordt in NL gebruikt alleen voor "inhalen" (van auto's, fietsen etc.), zou vervangen met "aangeven" (meestal zonder "even" maar mag wel)
557: "gaan" is onnodig
562: "recycleren" => "recyclen" (BE/NL)
567: "ank" => "bank"
568: "De" onnodig
570: "is aan het lossen" => "komt los" (BE?/NL)
579: "mopjes" => "grappen" (BE/NL)
579: "maar toch probeert hij" => "maar hij probeert toch"
582: "poetsvrouw" =>"schoonmaakster" (BE/NL)
583: "poetsman" => "schoonmaker" (BE/NL) (Firefox spellingchecker kent alleen 'poetsvrouw' :O)
584: "met de motorfiets rijdt" => "op de motorfiets rijdt" (of " op de motor rijdt" )
585: "performant" ken ik niet, denk "efficiënt"?(BE/NL)
596: "gevandaliseerd" => "gesloopt"/"beschadigd" (BE/NL)
599: "best" wordt niet zo in NL gebruikt
600: een komma voor "nadat"
600: tijd en koppelwoord loopt niet "zijn .. nadat .. is gebroken" => "zijn .. nadat .. was gebroken"/"zijn .. toen .. is gebroken"
600: "zijn gebroken .. is gebroken" leest vreemd zou er "zijn gebroken .. ging" van maken

**Comment by sroet** [comment]
@danielsjf I read through the next 500 (this has been an amazing project to use for SOG (studie ontwijkend gedrag).

**Comment by mikehenrty** [comment]
please flag me when this PR is ready

**Comment by sroet** [comment]
This comment will be used for sentences 1000-1500
I read until sentence 1100:
1001: "De"  =>  "Die" (leest beter, vind ik)
1002: "met twee" => "met zijn tweeen"/"met twee man"
1005: "van" onnodig
1006: "aan de viersprong" => "op het kruispunt" (BE?/NL)
1023 "verzameld" => "verzamelt" (actief werkwoord)
1024 "maximaal" => "maximale" (staat beter tegenover "minimale")
1027: "Het laatste avondmaal" => "Het Laatste Avondmaal" (het is een historische gebeurtenis)
1034: "Waar" => "Waarheen"
1039: "Toog" => "Bar" (BE/NL)
1040: "best" wordt niet gebruikt in NL
1041: "zou beter stoppen" => "zou beter kunnen stoppen" (BE?/NL)
1045 "kraantjeswater" => "kraanwater" (BE?/NL)
1054: "non" => "een non"
1065: "normaal" => "normaal gesproken" (BE?/NL)
1067: "in te steken" => "erin te steken" (BE?/NL)
1069: "liggen" => "rijden"
1070: "haag" => "heg" (haag is ouderwets in NL maar kan wel)(BE/NL)
1074: "had hij niet zo graag" => "mocht hij niet zo" (BE/NL)
1079: "gitzwart" => "gitzwarte"
1083: "aan" => "met"
1084: "tijden" => "tijd" (BE?/NL)
1087: "enkel" => "alleen" (BE/NL)
1092: "het zomeruur" => "de zomertijd" (BE?/NL)
1093: "het winteruur" => "de wintertijd" (BE?/NL)
1100: "verloren gelopen" => "verdwaald" (BE?/NL)

**Comment by sroet** [comment]
@danielsjf until 1500 is done now. 
These are still very nice sentences to read, thank you for the time to put this together!

**Comment by danielsjf** [comment]
Updated the file until line 1230. More to come when I find time tomorrow. Thanks for reading and checking them!

Mazout is stookolie :-) One of the most Belgian words in the sentences, but still often used. Maybe we should find a way to add the region data to some sentences.

**Comment by danielsjf** [comment]
@sroet denk je dat je nog tijd hebt om de volgende 1000 na te lezen? Indien niet zal ik er zelf nog eens doorgaan en deze voorlopig al toevoegen. Van hieruit kunnen we dan incrementeel verderwerken.

**Comment by sroet** [comment]
@danielsjf bedankt voor de ping. Ik denk het niet voor eind augustus/begin september. Dus als jij er nog een keertje doorheen kan lopen dan is het wat mij betreft ok.
De rest kan zoals de Duitse/Franse corpus gedaan worden (incidentele PR's met fixes).

**Comment by danielsjf** [comment]
@sroet ok perfect, dan doen we het zo. Zal het in het weekend proberen te finaliseren.

**Comment by danielsjf** [comment]
@mikehenrty, this one is ready to merge.

**Comment by danielsjf** [comment]
@gregoor, don't know if you are the right one to ping, but this one is ready to merge and Mikehenrty seems absent.

**Comment by Gregoor** [comment]
Michael is on vacation for ~2 more weeks. So yes, pinging me in the meantime is the way to go 👍

**Pull request merged**
