### PR TITLE
Specify size for check boxes

### PR DESCRIPTION
**Pull request by DeathCamel57**
Proposed fix for #178

### CODE REVIEW

**Comment by DeathCamel57** [comment]
This should line up the text on the checkbox line, with the line below it.

**Comment by mikehenrty** [comment]
Thanks for the contribution @DeathCamel57!

The issue #178 is about text alignment with the below the check "I'd like to stay informed..". Your change only deals with the current line.

**Comment by DeathCamel57** [comment]
@mikehenrty Though the change only affects the first line, the line below it already has a padding of 1 rem. So making the checkbox 1rem wide and tall makes the two lines line up properly.
screenshot from 2017-07-25 14-52-07

**Comment by DeathCamel57** [comment]
Adding a pipe at the start of both lines makes it clear that they now line up. The pipe is not a code change, just a developer tools edit to show that they line up. The pipes ** are not** added to the code
screenshot from 2017-07-25 14-55-14

**Comment by mikehenrty** [comment]
Oh, so sorry! I missed that somehow. Approved :)

**Pull request merged**
