### PR TITLE
Create cities2.txt

### PR DESCRIPTION
**Pull request by jmontane**
Town names from Andorra, Balearic Islands, Catalonia and Valencia, similar to cities.txt

### CODE REVIEW

**Comment by nukeador** [comment]
Hello @jmontane 

The process to incorporate new sentences to Common Voice is not longer github PR. For quality assurance, we ask everyone to use the sentence collector tool

https://common-voice.github.io/sentence-collector/#/

Thanks!

**Comment by jmontane** [comment]
Really? Will we unable to PR Wikipedia extracted sentences? What does it happens if an author donate us a book under CC0 license?

For small communities (i. e. few people), it's a bad criteria forcing sentence collector tool

About cities2.txt, it's very similar to cities.txt, if you compare both files.

**Comment by fitojb** [comment]
@nukeador Ping?

**Comment by nukeador** [comment]
Hi,

Wikipedia sentences in Catalan have been already incorporated following the sentence scrapper process.

For other large sources of text we are still missing a better process, that we want to solve as soon as we automate the wikipedia one first.

The only reliable way we have right now is the sentence collector.

Thanks for your understanding.

**Comment by fitojb** [comment]
So you don’t have “a better process” but meanwhile you block one that is reliable, fast and can be easily vetted by the language communities. I don’t understand why Mozilla keeps on shooting itself on the foot while it reinvents the wheel. First by dropping Pootle for its inferior Pontoon, now it doesn’t want to leverage Git. Funny.

**Comment by nukeador** [comment]
Adolfo, I understand your frustration but please understand that our main priority is to ensure the quality of the data that is incorporated into our dataset, the previous process you are advocating for proved itself unreliable and introduced risks to the project.

At the end of 2018 we had major issues for not having a more strict process and that took our small team a lot of hours to fix, we want to avoid that and we want to ensure we don't have to do a major clean-up again in the future. Sentence collector has been the only way we had to ensure the quality standards needed for this project.

Having said that, if you have ideas to improve the current process they are more than welcome, please chime in the project discourse:

https://discourse.mozilla.org/c/voice

Thanks!

**Pull request closed without merging**
