### PR TITLE
Add Bahasa Indonesia Sentences

### PR DESCRIPTION
**Pull request by serabiasin**
most of these text comes from my mind and some of them i got from book

### CODE REVIEW

**Comment by serabiasin** [comment]
@mikehenrty

**Comment by mikehenrty** [comment]
thanks @serabiasin! Where did these sentences come from? Did you write them yourself? Have you had anyone proofreading them?

**Comment by serabiasin** [comment]
most of these sentences are made by myself  and the last ten of the sentences are from article, i modified to be shorter sentences. for the proofreading i checked the vocabulary based on KBBI (The Great Dictionary of the Indonesian Language) @mikehenrty

**Comment by mikehenrty** [comment]
Thanks for the info @serabiasin !

> the last ten of the sentences are from article

What article? Most likely this article is under some sort of copyright, which would mean we can't use it. I think the safest thing would be to remove those ten lines that come from the article (unless you wrote that article).

**Comment by serabiasin** [comment]
i already modified the last of ten sentences and added a few sentences @mikehenrty

**Comment by mikehenrty** [comment]
thank you @serabiasin !

**Pull request merged**
