### PR TITLE
Add DB replica in staging

### PR DESCRIPTION
**Pull request by The-smooth-operator**

### CODE REVIEW

**Comment by gozer** [comment]
Curious here, with no references to a bug, difficult to determine why this is hapenning.

Especially only in staging and not in prod ?

**Comment by The-smooth-operator** [comment]
Hey @gozer sorry for not adding any description here, we tried getting your help by email, but decide to move on after not being replied.
We were trying to add a replica to the database, and wanted to try the behavior first in staging. Which by the way didn't succeed, seems like Terraform didn't apply the changes, or the change was not triggering the creation of a replica database.

**Comment by gozer** [comment]
> Which by the way didn't succeed, seems like Terraform didn't apply the changes, or the change was
> not triggering the creation of a replica database.

Not sure what leads you to believe that, I looked at the corresponding Terraform deploy and the AWS console, and the primary RDS database for stage does have a replica now, like expected. It worked just fine!

**Comment by The-smooth-operator** [comment]
Thank you Gozer, I somehow haven't seen it. I'll make sure to mention you in future PRs.

**Pull request merged**
