### PR TITLE
Create Sayingsfromallovertheworld.txt

### PR DESCRIPTION
**Pull request by MrLaaky**
Another batch of Slovenian sentences.
Reviewed and ready to use.

Question:
This sentences are common everyday in use sentences. Is there anything in plan to approach the vocabulary and use sentences in specific fields e.g. law, medicine, administration, ... ? Thank you for you time!
Kind regards

### CODE REVIEW

**Comment by mikehenrty** [comment]
> Is there anything in plan to approach the vocabulary and use sentences in specific fields e.g. law, medicine, administration, ... ?

Not at this time but it is indeed something we are looking at. For now, it is up to people in those industries who care about voice technology to upload the appropriate sentences.

Thanks for you contributions!

**Comment by mikehenrty** [comment]
Our approach to this is that some people may not know how to pronounce certain words. That is why we have the "Skip" button. And if someone mis-pronounces, then people should catch this in the validation phase.

**Comment by MrLaaky** [comment]
Haven't thought about it this way, but makes perfect sense. Thank you!

**Comment by mikehenrty** [comment]
you're welcome @MrLaaky, thank you for the help

**Pull request merged**
