### PR TITLE
First upload of 7440 italian sentences

### PR DESCRIPTION
**Pull request by Mte90**
This is a work made by the Mozilla Italia community members in the last weeks.

### CODE REVIEW

**Comment by Mte90** [comment]
Let's wait few hours because we are working on another review.

**Comment by mikehenrty** [comment]
Sure @Mte90, just flag me when this is ready to go in. Thank you for organizing this!

**Comment by Mte90** [comment]
ok another review made and is ready for production!

**Comment by mikehenrty** [comment]
Che bello!

**Comment by flodolo** [comment]
For transparency and completeness: there is an ongoing discussion within the Italian localization team about this file, and if this file should be backed out.

I'm not familiar with the workflow used in Common Voice, but let's hold on with Italian until all parties involved in this discussion have reached an agreement.

**Comment by mikehenrty** [comment]
@flodolo, @Mte90, can you give me some insight into that discussion? We were planning on launching Italian later this week. I can definitely hold off if there are issues.

**Comment by Mte90** [comment]
I think that today or tomorrow we will have the senteces reviewed more deeply.
The question is for the community (after this review) if the senteces are good, because we are afraid of quality of the text, split dialogs in senteces (as example) and many other details.

**Comment by mikehenrty** [comment]
@Mte90 great. let me know if i can help. feel free to submit a PR with the reviewed sentences whenever you are ready. thanks for you work!

**Pull request merged**
