### PR TITLE
Create corpus-June-2020.txt

### PR DESCRIPTION
**Pull request by mozillakab**
Corpus from https://github.com/mozillakab/Kabyletexts/   , a corpus dedicated initially to work on the Model Language along with the Model generated from DeepSpeech. 
Shared on Github under free use for everyone.

### CODE REVIEW

**Comment by mozillakab** [comment]
As SC is very slow right now to validate sentence,  we need more sentences on CV to keep contributors recording and validating. I'm afraid to redeploy the same effort to invite people to CV. Please would you like merge them?

**Comment by mbransn** [comment]
@mozillakab thanks for the PR and context, this will require QA to ensure sentences meet requirements (this is why the sentence collector can be slower, that upload and voting process ensures validation of sentence quality). For manual sentence PRs a Common Voice team member must process QA which requires time and the team is currently at capacity processing the next dataset release. The earliest we could get to this is possibly next week, pending availability of teammates who are currently offline for personal holiday. Thanks for your patience!

**Comment by mozillakab** [comment]
@mbransn thanks for reply, my only concern are contributors, I'd like keep the team (kab) involved as we were last moths.

**Comment by nukeador** [comment]
Hi @mozillakab 

From [our current documentation on discourse](https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530)

> If you have found an existing public domain corpus bigger than 100K sentences, we have an independent process to handle it, since we understand that manual validation using the sentence collector is not ideal.
>
> Please create a new topic here so we can evaluate if your corpus fits the license and size requirements to run this process. 
>
> :hammer: Skills needed: Expertise processing and cleaning up text, linguistics/language expertise to check the quality of the resulting sentences.

Please, [open a new topic on discourse](https://discourse.mozilla.org/c/voice/239) describing the source you want to incorporate, with a link to it, as well to a link to its license. Based on that, we will be able to evaluate if the source is valid for our independent QA process and if that's the case, provide you with the process to run the process and the QA, report back.

To avoid confusions, all of this needs to happen before having a PR here. I would suggest to close this PR until all the previous process has happened and we got green light.

I understand this might look more complex, but ensuring the quality and license of our text corpus is a fundamental piece for the success of the work.

Thanks for your understanding!

**Pull request closed without merging**
