### PR TITLE
Added a Content Security Policy header

### LINKED ISSUE #103: Add CSP header
This will increase our security rating our Nubis.

### PR DESCRIPTION
**Pull request by Omniscimus**
Fixes #103. The CSP header may be important for security (XSS prevention), especially when more user-generated content will be displayed to other users in the future, such as accent information. The browser will ignore content loaded from external websites, as well as inline scripts and CSS.

Couldn't test this properly due to #315. I did test the header by adding it in a meta tag to web/index.html. If the `media-src` directive is omitted, the browser refuses to load recorded audio, which appears to have a URI similar to `blob:https://voice.mozilla.org/ad3c9602-f211-4a28-88f2-f98f61bbe72f`.

Before being merged, this should be tested on a website where the Nubis stuff works. If the header contains mistakes, legitimate content may not load. I'm curious about downloading validation audio and recording audio, which I could not test properly either because I don't have an Amazon Cloud thing. Chrome logs CSP violations in its debug console, which may be useful.

**NOTE**: any inline CSS will be ignored by the browser with this CSP header. This appeared to be no problem, because it's all loaded from external stylesheets.

### CODE REVIEW

**Comment by mikehenrty** [comment]
Thanks @Omniscimus! @gozer could you take a look at this?

**Comment by mozfreddyb** [comment]
Here's an unsolicited drive-by security review from someone who knows CSP very well, but doesn't know your application and is totally *unaffiliated* with our service/website/infra security people:

This CSP is a security improvement 👍

**Comment by mikehenrty** [comment]
@gozer review ping?

**Comment by Omniscimus** [comment]
I just tested the header with the [Laboratory](https://github.com/april/laboratory) plugin and realized that it wasn't allowing Google Analytics to get through. Also, in the `media-src` directive, the AWS server had to be added because recordings are downloaded from there for validation. I believe that the domain of the AWS server is not always the same (please correct me if I'm wrong), so I couldn't make it any stricter than `https://*.amazonaws.com`.

Finally, with this CSP header, the browser console throws errors if `'unsafe-eval'` is not in the `script-src` directive, although everything seems to be working. `'unsafe-eval'` reduces the security benefits of the CSP header. The Web Console is giving me the following error:

`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://voice.mozilla.org https://www.google-analytics.com/analytics.js”). Source: call to eval() or related function blocked by CSP.`

According to the Browser Console, this is caused by **two** calls to `Function()`:

`Error: call to Function() blocked by CSP`

`bundle.js` does not contain a call to `Function()`. `analytics.js` does contain the word Function, but not a call to it, and even if I block the analytics script, the error remains. Does anyone have any idea where this could come from? This is the CSP I was testing:

`default-src 'self'; img-src 'self' https://www.google-analytics.com; media-src blob: https://*.amazonaws.com; script-src 'self' https://www.google-analytics.com/analytics.js`

**Comment by mikehenrty** [comment]
@Omniscimus thanks again for your help here.

I've been testing and playing around with some CSP settings, all based on your initial recommendation. I'm going to merge this, make some tweaks, and then push it to our staging server (voice.allizom.org) and test it. Hopefully we'll have this working very soon.

**Pull request merged**
