### PR TITLE
Sentence Collector - validated sentences export - 2019-02-01-20-10

### PR DESCRIPTION
**Pull request by nukeador**
This is the latest export, a lot of work in the past days.

However I'm not fully comfortable with the sentences approved for Spanish.

@maremoto I think you added the "Sonata" and I feel a lot of sentences there are weird to read.

Export log:

```
Starting export for ab..
Starting export for ace..
Starting export for ady..
Starting export for af..
Starting export for am..
Starting export for an..
Starting export for ar..
Starting export for as..
Starting export for ast..
Starting export for az..
Starting export for bg..
Starting export for bn..
Starting export for br..
Starting export for bxr..
Starting export for ca..
Starting export for cak..
Starting export for cnh..
Starting export for cs..
Starting export for cv..
Starting export for cy..
Starting export for da..
Starting export for de..
  - Found 260 approved sentences
  - Found 260 valid sentences
  - Writing all meta data to ./voice-web/server/data/de/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for de..
  - Got 6913 CV sentences..
  - Got 260 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/de/sentence-collector.txt..
Starting export for dsb..
Starting export for dv..
Starting export for el..
  - Found 3 approved sentences
  - Found 3 valid sentences
  - Writing all meta data to ./voice-web/server/data/el/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for el..
  - Got 0 CV sentences..
  - Got 3 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/el/sentence-collector.txt..
Starting export for en..
  - Found 703 approved sentences
  - Found 703 valid sentences
  - Writing all meta data to ./voice-web/server/data/en/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for en..
  - Got 5549 CV sentences..
  - Got 695 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/en/sentence-collector.txt..
Starting export for eo..
Starting export for es..
  - Found 5174 approved sentences
  - Found 5174 valid sentences
  - Writing all meta data to ./voice-web/server/data/es/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for es..
  - Got 0 CV sentences..
  - Got 5174 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/es/sentence-collector.txt..
Starting export for et..
Starting export for eu..
Starting export for fa..
Starting export for fi..
Starting export for fo..
Starting export for fr..
  - Found 7 approved sentences
  - Found 7 valid sentences
  - Writing all meta data to ./voice-web/server/data/fr/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for fr..
  - Got 36457 CV sentences..
  - Got 7 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/fr/sentence-collector.txt..
Starting export for fy-NL..
Starting export for ga-IE..
Starting export for he..
Starting export for hsb..
Starting export for hu..
Starting export for ia..
Starting export for id..
  - Found 61 approved sentences
  - Found 61 valid sentences
  - Writing all meta data to ./voice-web/server/data/id/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for id..
  - Got 106 CV sentences..
  - Got 61 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/id/sentence-collector.txt..
Starting export for is..
Starting export for it..
Starting export for ja..
Starting export for ka..
Starting export for kab..
  - Found 912 approved sentences
  - Found 912 valid sentences
  - Writing all meta data to ./voice-web/server/data/kab/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for kab..
  - Got 16661 CV sentences..
  - Got 904 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/kab/sentence-collector.txt..
Starting export for kk..
Starting export for ko..
Starting export for kpv..
Starting export for kw..
Starting export for ky..
Starting export for mdf..
Starting export for mhr..
Starting export for mk..
Starting export for mn..
Starting export for mrj..
Starting export for myv..
Starting export for nb-NO..
Starting export for ne-NP..
Starting export for nl..
Starting export for nn-NO..
Starting export for oc..
Starting export for or..
Starting export for pl..
Starting export for pt-BR..
Starting export for rm-sursilv..
Starting export for ro..
Starting export for ru..
Starting export for sah..
Starting export for sc..
Starting export for sk..
Starting export for sl..
Starting export for sq..
Starting export for sr..
Starting export for sv-SE..
Starting export for ta..
Starting export for te..
Starting export for th..
Starting export for tr..
Starting export for tt..
Starting export for uby..
Starting export for udm..
Starting export for uk..
Starting export for ur..
Starting export for uz..
Starting export for vi..
Starting export for vot..
Starting export for zh-CN..
Starting export for zh-HK..
Starting export for zh-TW..
Duration to export everything (ms):  117506
Done in 123.72s.
```

### CODE REVIEW

**Comment by nukeador** [comment]
Hi @maremoto 

We need to fix it on the sentence collector, if not, the sentences will be exported again in the next batch.

The tricky part is that for some reason 3 people voted positive for these sentences, which is a problem. 

@MichaelKohler We would need something over the sentence collection to allow sentence author to remove his own sentences or something like that? What would be the easiest solution?

**Comment by nukeador** [comment]
@Gregoor Also I don't want the rest of the work to be blocked by this concern, so I would like to hear your recommendation for this pull request.

We can probably merge and then fix the problematic Spanish sentences later, I suspect it's not uncommon to have some invalid sentences in other languages until we found and fix them.

**Comment by nukeador** [comment]
Updating the export.

Sentence Collector - validated sentences export - 2019-02-02-16-03
```
Starting export for ab..
Starting export for ace..
Starting export for ady..
Starting export for af..
Starting export for am..
Starting export for an..
Starting export for ar..
Starting export for as..
Starting export for ast..
Starting export for az..
Starting export for bg..
Starting export for bn..
Starting export for br..
Starting export for bxr..
Starting export for ca..
Starting export for cak..
Starting export for cnh..
Starting export for cs..
Starting export for cv..
Starting export for cy..
Starting export for da..
Starting export for de..
  - Found 450 approved sentences
  - Found 450 valid sentences
  - Writing all meta data to ./voice-web/server/data/de/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for de..
  - Got 6913 CV sentences..
  - Got 450 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/de/sentence-collector.txt..
Starting export for dsb..
Starting export for dv..
Starting export for el..
  - Found 3 approved sentences
  - Found 3 valid sentences
  - Writing all meta data to ./voice-web/server/data/el/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for el..
  - Got 0 CV sentences..
  - Got 3 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/el/sentence-collector.txt..
Starting export for en..
  - Found 703 approved sentences
  - Found 703 valid sentences
  - Writing all meta data to ./voice-web/server/data/en/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for en..
  - Got 5549 CV sentences..
  - Got 695 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/en/sentence-collector.txt..
Starting export for eo..
Starting export for es..
  - Found 5899 approved sentences
  - Found 5899 valid sentences
  - Writing all meta data to ./voice-web/server/data/es/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for es..
  - Got 0 CV sentences..
  - Got 5899 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/es/sentence-collector.txt..
Starting export for et..
Starting export for eu..
Starting export for fa..
Starting export for fi..
Starting export for fo..
Starting export for fr..
  - Found 7 approved sentences
  - Found 7 valid sentences
  - Writing all meta data to ./voice-web/server/data/fr/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for fr..
  - Got 36457 CV sentences..
  - Got 7 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/fr/sentence-collector.txt..
Starting export for fy-NL..
Starting export for ga-IE..
Starting export for he..
Starting export for hsb..
Starting export for hu..
Starting export for ia..
Starting export for id..
  - Found 61 approved sentences
  - Found 61 valid sentences
  - Writing all meta data to ./voice-web/server/data/id/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for id..
  - Got 106 CV sentences..
  - Got 61 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/id/sentence-collector.txt..
Starting export for is..
Starting export for it..
Starting export for ja..
Starting export for ka..
Starting export for kab..
  - Found 1121 approved sentences
  - Found 1121 valid sentences
  - Writing all meta data to ./voice-web/server/data/kab/sentence-collector.json..
  - Cleaning up sentences
  - Getting CV sentences for kab..
  - Got 16661 CV sentences..
  - Got 1113 sentences not already existing in CV..
  - Writing all sentences to ./voice-web/server/data/kab/sentence-collector.txt..
Starting export for kk..
Starting export for ko..
Starting export for kpv..
Starting export for kw..
Starting export for ky..
Starting export for mdf..
Starting export for mhr..
Starting export for mk..
Starting export for mn..
Starting export for mrj..
Starting export for myv..
Starting export for nb-NO..
Starting export for ne-NP..
Starting export for nl..
Starting export for nn-NO..
Starting export for oc..
Starting export for or..
Starting export for pl..
Starting export for pt-BR..
Starting export for rm-sursilv..
Starting export for ro..
Starting export for ru..
Starting export for sah..
Starting export for sc..
Starting export for sk..
Starting export for sl..
Starting export for sq..
Starting export for sr..
Starting export for sv-SE..
Starting export for ta..
Starting export for te..
Starting export for th..
Starting export for tr..
Starting export for tt..
Starting export for uby..
Starting export for udm..
Starting export for uk..
Starting export for ur..
Starting export for uz..
Starting export for vi..
Starting export for vot..
Starting export for zh-CN..
Starting export for zh-HK..
Starting export for zh-TW..
Duration to export everything (ms):  100638
Done in 107.06s.
```

**Comment by MichaelKohler** [comment]
> @MichaelKohler We would need something over the sentence collection to allow sentence author to remove his own sentences or something like that? What would be the easiest solution?

https://github.com/Common-Voice/sentence-collector/issues/118

**Comment by nukeador** [comment]
@maremoto Currently the collector doens't have that ability. We need to check with @MichaelKohler what's easier to implement, allow users to remove their own sentences or something else.

**Comment by dabinat** [comment]
I feel like the biggest problem here isn’t that the sentences were bad, but that they passed validation regardless. The whole purpose of validation is to prevent that.

So is this a case of requiring more votes to validate? Or do validators need more guidelines?

**Pull request merged**
