### PR TITLE
Add editorconfig

### LINKED ISSUE #849: Editorconfig
I would add .editorconfig so the code will be formatted the same in every editor that respects editorconfig. What do you think @Gregoor?

### PR DESCRIPTION
**Pull request by MekliCZ**
fixes #849

### CODE REVIEW

**Comment by Gregoor** [comment]
Works 👍 Maybe we should use this as an opportunity to make existing css files conform to this?

**Comment by MekliCZ** [comment]
I can reformat them all, if you want.

**Comment by Gregoor** [comment]
That'd be great! For some reason I can't push to this branch directly, even though GitHub is telling me it should be possible 😒

**Comment by MekliCZ** [comment]
@Gregoor Are you now able to push to my branch? I have added you as an collaborator. This is definetly not my last PR so it will be useful in the future. :)

**Comment by Gregoor** [comment]
That did work, thank you :)

**Pull request merged**
