### PR TITLE
add  server/data/zh-CN/cn.txt

### PR DESCRIPTION
**Pull request by hwl311**
add  server/data/zh-CN/cn.txt

### CODE REVIEW

**Comment by mikehenrty** [comment]
hi @hwl311, thank you for the sentences!

can you tell us the source of these sentences? and have they been reviewed for grammar?

**Comment by mikehenrty** [comment]
@hwl311, I mean: where did these sentences come from? Do you own the copyright, or are they public domain?

**Comment by mikehenrty** [comment]
oh, I see, you converted the traditional chinese to simplified?

**Comment by hwl311** [comment]
yes

**Comment by mikehenrty** [comment]
great, thank you @hwl311

**Pull request merged**
