### PR TITLE
Enable Russian. They have more than 5K

### PR DESCRIPTION
**Pull request by nukeador**

### CODE REVIEW

**Comment by mikehenrty** [comment]
@highsource will be happy about this :)

**Comment by Gregoor** [comment]
Neat! It's now contributable on master > 671ef1c1e3922544f0c36afaaca7a91b84751a86

We have a script that checks which languages are new/contributable/rtl etc., in the future run that or ping me:
https://github.com/mozilla/voice-web/blob/master/CONTRIBUTING.md#import-languages

**Comment by highsource** [comment]
I somehow don't see how I contribute to Russian yet?

I'm registered an I've added Russian as one of the languages in my profile.

https://voice.mozilla.org/ru/listen redirects to https://voice.mozilla.org/ru, I don't come to pages where I can listen or speak

**Comment by nukeador** [comment]
Changes will be live in the next deployment.

**Pull request closed without merging**
