### PR TITLE
fixed register section layout response

### PR DESCRIPTION
**Pull request by mritunjayz**

### CODE REVIEW

**Comment by Gregoor** [comment]
Is this related to some issue and if not where does the problem occur?

**Comment by mritunjayz** [comment]
Sorry, for the no description!
Yeah, problem in width on home page of register section if you are not login. https://voice.mozilla.org/en

**Comment by mritunjayz** [comment]
didn't you get this ? @gregoor

**Comment by Gregoor** [comment]
I did, just had a busy week. Thanks for the patience. 

Just looked at it and I don't think it does what we want. This limits the spread of the background waves. We do want them to be fullscreen.

**Comment by rileyjshaw** [comment]
The issue this addresses was fixed in https://github.com/mozilla/voice-web/pull/2255.

**Pull request closed without merging**
