### PR TITLE
Sentence Collector Export Dec 18 2019

### PR DESCRIPTION
**Pull request by phirework**
I know this is usually @MichaelKohler's purview but I wanted to make sure that I knew how to run the SC export in case MK isn't around, and also we wanted to deploy to prod this week to avoid deploying something two days before everyone leaves for two weeks so we needed an export asap. Can you review @nukeador?

cc @mbransn

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Can you also run a `import-locales` to update the locales? At least Romanian should as far as I see now be available for collection.

Then https://github.com/mozilla/voice-web/pull/2471 and https://github.com/mozilla/voice-web/pull/2473 can be closed as this one here is newer.

**Comment by phirework** [comment]
Awesome, thanks for the quick reply @MichaelKohler!!

**Comment by mbransn** [comment]
Thanks both, awesome to see!!

**Comment by nukeador** [comment]
This is great, @phirework I hope the instructions I created to export and merge the sentences were clear enough to follow! :-)

**Comment by phirework** [comment]
@nukeador They were great, thank you for documenting all that!

**Pull request merged**
