### PR TITLE
Create copus-hocine11.txt

### PR DESCRIPTION
**Pull request by mozillakab**
Files 36 37 38 39 40 41 from Hocine: https://github.com/Hociben/corpus-kabyle
CC0 licensed sentences

### CODE REVIEW

**Comment by mozillakab** [comment]
@Gregoor 
500 more CC0 sentences from Hocine. 
Source https://github.com/Hociben/corpus-kabyle   
Please would you like merge them?
Thanks

**Comment by Gregoor** [comment]
@mozillakab have you started using the sentence collection tool:
https://discourse.mozilla.org/t/sentence-collection-tool-february-2019-milestone-discussion/35166
?

**Comment by mozillakab** [comment]
Yes @Gregoor but just I tested it.
I didn't talked about it to the team to avoid collectin a huge amount of sentences with errors. 
We have to make an admin/admins before starting. We can"t open it for everyone now.

**Comment by mozillakab** [comment]
@Gregoor Thanks I'll check again right now.

**Comment by nukeador** [comment]
Note we will launch the sentence collector tool beta next week and notify everyone. You will be able to c&p the sentences there and the tool will do most "hard requirement" validations. Then the review system will make sure enough people have reviewed and vote positively.

**Comment by mozillakab** [comment]
@nukeador 
The best to do is to involve students, teachers from the language departments as well as writers as I'm doing now with the kab corpus. I think linguistic corpora is not matter of vote. While we can expose the voice to people to vote, text should not follow the same process (vote) I think. Of course, at the moment we are spending a lot of time to correct sentences sent by people on Github, FB groups, Emails...and we still getting errors, we  hope getting a usable  and easy tool to correct and review.

**Comment by nukeador** [comment]
Yes, that's our goal, the tool should facilitate and speed up exactly what you mentioned.

**Comment by mozillakab** [comment]
@Gregoor These sentences are also uploaded on the sentence collector. should I close this PR?

**Comment by nukeador** [comment]
Hey, please, hold on.

As we inform over slack today we are currently cleaning up the database, your sentences will be removed. We plan to launch the beta today, please wait for the announcement in a few.

Thanks!

**Comment by mozillakab** [comment]
I'm closing this PR. Sentences were added with Sentence Collector.

**Pull request closed without merging**
