### PR TITLE
Fix typos and improve organization in iOS view controllers

### PR DESCRIPTION
**Pull request by lukereichold**
Proposing several fixes / enhancements surrounding view controller classes of the iOS app:
- Fix incorrect access modifiers and typos in string literals
- Make code organization / formatting consistent in `ViewController.swift` and `BrowserViewController.swift`

### CODE REVIEW

**Comment by mikehenrty** [comment]
Thanks for the improvements @lukereichold ! Unfortunately, our iOS developer is no longer with the project, and I have no way of testing these changes. Perhaps someone from the community could help us review a build with these changes? Adding help wanted tag to that end.

**Comment by AndrewLauder** [comment]
It looks ok to me. Main changes were adjusting privacy of variables and functions.

**Comment by MichaelKohler** [comment]
Should this be merged or does somebody want to update this with the latest info about native apps and we go from there?

**Comment by phirework** [comment]
@MichaelKohler Given the many transitions on the project since these proposed changes, even if this were merged we have no way of getting a new release to the Apple Store. The plan is ultimately to stop supporting the iOS app and figuring out a way of moving to a fully mobile web experience (for a bunch of reasons, not the least of which is that authentication is a nightmare) so I'm inclined to say let's close it.

**Pull request closed without merging**
