### PR TITLE
add th-TH

### PR DESCRIPTION
**Pull request by wannaphongcom**
Wannaphong.txt is produced by myself.

### CODE REVIEW

**Comment by mikehenrty** [comment]
hi @wannaphongcom ! thanks for these. did you write these sentences? has anyone proofread them?

**Comment by wannaphongcom** [comment]
Yes , I did. I proofread all sentences.

**Comment by veer66** [comment]
@mikehenrty I just proofread it couple minutes ago. Do you want me to look at any particular aspect of these sentences?

**Comment by mikehenrty** [comment]
@veer66 thank you! i just wanted to make sure someone other than the writer had a look at these sentences. it's our informal policy.

thanks for the sentences @wannaphongcom !

**Pull request merged**
