### PR TITLE
Remove all sentences for Ukrainian

### PR DESCRIPTION
**Pull request by a-polivanchuk**
All the sentences are incorrect and should be removed.
Please clean up the file completely.
https://discourse.mozilla.org/t/remove-all-sentences-in-sentence-collector-for-ukrainian/47927

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Sorry, forgot about that discussion. Will do this within the next few days.

**Comment by a-polivanchuk** [comment]
NP, I've just checked out that the number of approved sentences got increased...

**Comment by phirework** [comment]
@MichaelKohler can this be merged?

**Comment by MichaelKohler** [comment]
Not yet, first I need to remove those from the Sentence Collector DB as well. In the end the export resulting from that will decide about the faith of this PR, but right now it sounds like it will be the same and we will eventually be able to just merge this.  Will report back :)

**Comment by MichaelKohler** [comment]
This is now superseded by https://github.com/mozilla/voice-web/pull/2504/files#diff-01f1adf371e128299c22ed64867e375b and can be closed.

**Pull request closed without merging**
