### PR TITLE
Add polyfill for Promise

### LINKED ISSUE #142: [Win10] The app doesn't load on IE11
[Affected versions]:
- Microsoft IE11

[Affected platforms]:
- Win 10 x64

[Steps to reproduce]:
1. Open https://voice.allizom.org/

[Expected result]:
The app is displayed and works properly /
If the browser is not supported, there should be an error message explaining this.

[Actual result]:
The app doesn't load, black circle spins forever

### PR DESCRIPTION
**Pull request by kenrick95**
Added this polyfill: https://github.com/taylorhakes/promise-polyfill

Fixes #142

### CODE REVIEW

**Comment by kenrick95** [comment]
This is how polyfilled voice-web project looks like on IE11 on Windows 10.

capture-polyfilled

Something still feels broken, probably due to usage of CSS variable?

capture-css

**Comment by mikehenrty** [comment]
Great! Thanks for your help @kenrick95 !

**Comment by mikehenrty** [comment]
@kenrick95 here's our integration server with your changes:
https://voice.allizom.org/

What do you think, can we call this fixed?

**Comment by mikehenrty** [comment]
Whoops, wrong issue, please ignore.

**Pull request merged**
