### PR TITLE
add zh-tw sentences from Taipei Sprint and g0v hackathon

### PR DESCRIPTION
**Pull request by irvin**

### CODE REVIEW

**Comment by Gregoor** [comment]
Great! Have they been reviewed / could we put them in the sentence collector to make sure they fit the rules?

**Comment by irvin** [comment]
@Gregoor Yes, We had check them together in the end of event, and I had also review each single of them. 
Please if we could avoid put them into sentences collector, because that would also me again to review (and we have few thousand more sentences in the coming weeks)

**Comment by irvin** [comment]
(totally 2980 new sentences for now)

**Comment by irvin** [comment]
after discuss with the local community members, we decides to dump all the sentences into collection tools.

**Pull request closed without merging**
