### PR TITLE
kabyle corpus part1

### PR DESCRIPTION
**Pull request by belkacem77**
Corpus part one extracted from novels, short stories, daily language, proverbs

### CODE REVIEW

**Comment by mikehenrty** [comment]
hi @belkacem77, has this corpus been reviewed for grammar and spelling mistakes?

**Comment by belkacem77** [comment]
Yes, but needs a second review. It's the same corpus I used on my pos tagger project (KabyleNLP on Github and GitLab).

**Comment by belkacem77** [comment]
@mikehenrty , there is something special in Kabyle language we have a long list of affixed pronouns with three mophological forms (short, medium and long), i should use them all, so our corpus would be rather long in the future.

**Comment by mikehenrty** [comment]
hi @belkacem77, i'm not sure i understand. is the corpus in this PR still needing a review? or can I merge it?

**Comment by belkacem77** [comment]
hi @mikehenrty you can now merge it. I reviewed it.

**Comment by mikehenrty** [comment]
\o/ thanks @belkacem77 !

**Comment by belkacem77** [comment]
@mikehenrty thanks for you Mike

**Pull request merged**
