### PR TITLE
Split up CSS into multiple files

### PR DESCRIPTION
**Pull request by Gregoor**
Issue #478 

- adds `gulp-cssimport` as a dev dependency
- moves CSS into `src/` and splits it up into multiple files, by page or component
- as most page-specific rules were already grouped, the imports are placed in the `index.css` at the location these rule-groups were before, to not change how it cascades

### CODE REVIEW

**Comment by mikehenrty** [comment]
Great work @Gregoor! I love that we cascade building our stylesheet using imports rather than simply slurping up all the css files. This is definitely the way to go.

I wonder about moving all the css into the TypeScript source folders. To me, I like having the CSS in separate locations, even if the CSS structures mimics the TS structure somewhat. For instance, I'm not sure how much sense it makes to have the general CSS file located in the components sub folder. That said, I'm not familiar with idiomatic React, so maybe this is what people prefer? What are you thoughts on this decision?

@nevik or @kenrick95, if either of you have thoughts about this, I would love to hear them! We'll probably merge this in some form in the next day or 2.

Thanks!

**Comment by Gregoor** [comment]
Thanks @mikehenrty!

Personally I prefer having files that I touch at similar times near to each other, which is why I went with that way of structuring it. But if all of you prefer it to be more separated, I could also move the styles back to its own dir with pages & components subdir.

I think the React community's position on this is even more extreme (which I'm also very much on board with, as I hinted at in #478), namely CSS-in-JS. Imo the key reasons for going down that route are:
- every dependency is managed in JS
  - no more dead selectors
  - explicit reference to styles that are used, where I'd consider selectors to be more indirect
- no cascade, unless you explictly want it

In the case of styled-components (and some other CSS-in-JS) libraries it still outputs regular ol' stylesheets. So there is not really a downside to it (apart that you give up on some CSS features).
If that route is also interesting to you, I could create a PR where I apply styled-component to a single small page, to hopefully convince you of the benefits.

**Comment by mikehenrty** [comment]
Sounds interesting! Let's not go down the route of CSS directly in JSX components just yet, but I'm fine with heading that direction by moving CSS next to components. It looks like @kenrick95 agrees with you. Let's give @nevik a day or so to weigh in, and if not we'll merge this. In the meantime, let's keep the conversation open about CSS in JS.

**Comment by kenrick95** [comment]
Personally, I like related things to be grouped together, i.e. if a style is being used in a component, I like this style and component to be located together. One nice thing about this is that at code editors, usually there will be a tree-style navigation and when editing a component, those related files will be directly seen together instead of having to traverse to somewhere far away to look for related files. I think for a small project, navigation wasn't a big issue, but if a project became big and has a deep hierarchical component, it could be even more troublesome to find a CSS file related to a component.

----

Anyway, from my experience, there are many ways of importing style in React, but from what I observe, there isn't any clear "winner" of which CSS import style out there as each import style have its own advantages and disadvantages over the others.

**Comment by Gregoor** [comment]
@mikehenrty Fair enough, I'm fine with not rushing into it :)

@kenrick95 I agree, also on the winner-part. styled-components is probably more of a personal favorite. I'd be curious to hear what your prefered approach is.

**Comment by nevik** [comment]
LGTM ;)

(I had a longer reply, but the network swallowed it and GitHub doesn't keep it in the form until when it submits. So the above is a short summary :D )

**Comment by mikehenrty** [comment]
> (I had a longer reply, but the network swallowed it and GitHub doesn't keep it in the form until when it submits. So the above is a short summary :D )

I hate when that happens!

**Comment by mikehenrty** [comment]
Thanks everyone for the great discussion. Common Voice is very lucky to have such thoughtful contributors.

Onwards and upwards!

**Pull request merged**
