### PR TITLE
new persian sentences

### PR DESCRIPTION
**Pull request by herotux**
please merge :rose:

### CODE REVIEW

**Comment by Gregoor** [comment]
Did someone proof-read these? And are they all CC0?

**Comment by herotux** [comment]
yes checked and cc0 license:

**Comment by herotux** [comment]
https://github.com/herotux/mozilla-voice-fa

**Comment by imanmoghimiq30** [comment]
@Gergoor
Please check our github repository

**Comment by herotux** [comment]
Thanks @imanmoghimiq30

**Comment by Gregoor** [comment]
Great, I'll take your word for it :)

**Comment by imanmoghimiq30** [comment]
Good deal thanks

**Pull request merged**
