### PR TITLE
fix conversion errors in simplified chinese scripts

### PR DESCRIPTION
**Pull request by isofew**
As discussed in [this thread](
https://discourse.mozilla.org/t/errors-occur-when-traditional-chinese-characters-are-converted-to-simplified-chinese-characters/51005), there are some errors when traditional chinese scripts are automatically converted to simplified ones, the two most noticable ones being '着名' and '干隆'. So I just corrected these two words in the script and send this pull request.

### CODE REVIEW

**Comment by nukeador** [comment]
Thanks for the PR. I'm requesting review from other native speakers on the community.

**Comment by nukeador** [comment]
@irvin will help review this

**Comment by isofew** [comment]
> 
> 
> @irvin will help review this

Thanks for referring me to @irvin Hope this will get reviewed soon.

Also I noticed that some of the scripts are really not suitable for speaking (the phrase too rare or the style too formal). Do you know how and where I can contribute to scripts?

**Comment by irvin** [comment]
the PR is good. over to @nukeador

**Comment by irvin** [comment]
@isofew the script is here https://github.com/Common-Voice/cv-sentence-extractor
I don't think we will extracting sentences from Wikipedia again soon. 
Feel free to remove those hard sentences by creating another PR.

**Pull request merged**
