### PR TITLE
Add pa-IN

### PR DESCRIPTION
**Pull request by MichaelKohler**
pa-IN has collected and approved sentences, but those got never exported, as the Sentence Collector used "pa" and voice-web uses "pa-IN". I've now added that mapping in the Sentence Collector Export so we get those sentences too.

### CODE REVIEW

**Comment by MichaelKohler** [comment]
@nukeador r?

**Comment by nukeador** [comment]
What I'm thinking is that we should probably ask @peiying2 to use locale codes without country names, in this case "pa" following this standard

https://www.unicode.org/cldr/charts/latest/supplemental/languages_and_scripts.html

**Comment by phirework** [comment]
@nukeador Are we waiting on a verdict from Peiying or can this be merged?

**Comment by nukeador** [comment]
Let's go for this now. But we really need to review standardize our locale list to match with that unicode one, that will imply changes on the codes from pontoon that will have to be reflected on our side.

**Pull request merged**
