### PR TITLE
Fixed mistakes

### PR DESCRIPTION
**Pull request by mansayk**
This patch fixes orthographic mistakes in Tatar sentences.

### CODE REVIEW

**Comment by nukeador** [comment]
Hi,

The procedure to add new sentences is to go through the sentence collector tool to ensure they fit all the requirements:

https://common-voice.github.io/sentence-collector/

If sentences have errors in the files created before the sentence collector, we will just accept removal PRs here.

Thanks for your contributions!

**Comment by mansayk** [comment]
Could you please explain, how can we fix mistakes in current texts?

**Comment by nukeador** [comment]
You'll need to create a PR here only removing the sentences with mistakes and then send the fixed ones through the sentence collector tool.

**Comment by mansayk** [comment]
Ok, I understand the procedure now. Thank you!

**Pull request closed without merging**
