### PR TITLE
Add Nepal, Bangladesh and Afghanisthan in the South Asian Accent

### PR DESCRIPTION
**Pull request by roshangm1**
I have not included Bhutan and Maldives because I think they have different accents(although being South Asian Country)

### CODE REVIEW

**Comment by roshangm1** [comment]
Proposed solution for issue #662

**Comment by mikehenrty** [comment]
@kdavis-mozilla does this fit within your guidelines?

**Comment by kdavis-mozilla** [comment]
Generally we've taken the tack that we list countries where English is an official or recognised language.

Is this the case for Nepal, Bangladesh, and Afghanisthan? For example the English and Nepali wikipedia pages for both say English is not an official or recognised language in Nepal.

**Comment by nirmalrizal53** [comment]
@kdavis-mozilla Nepal is well popular in Nepal.  but I don't have much idea for other two countries. May be, I can resend pull request by including only Nepal in the list.

**Comment by kdavis-mozilla** [comment]
@nirmalrizal53 Is English an official or recognised language in Nepal?

**Comment by nirmalrizal53** [comment]
@kdavis-mozilla Yes, English is recognised language in Nepal.

**Comment by kdavis-mozilla** [comment]
@nirmalrizal53 I'm not really familiar with Nepal's languages. All the references I've seen for Nepal say English isn't an official or recognised language. Do you have references indicating English is a official or recognised language?

**Comment by asgs** [comment]
This [reference from Monologue.com] (https://www.ethnologue.com/country/NP/status) could be of use. English is categorized under Educational languages.

**Comment by mapmeld** [comment]
separate issue @roshangm1  : spelling of "Afghanistan"

**Comment by roshangm1** [comment]
I just removed Afghanistan and Bangladesh from the list because I am not sure about them.

**Comment by nukeador** [comment]
We will be opening a discussion with a proposal for accents in the coming days, please check the project Discourse and engage in the conversation with your input.

https://discourse.mozilla.org/c/voice

**Pull request closed without merging**
