### PR TITLE
Implement read/write isolation using different connection pools

### PR DESCRIPTION
**Pull request by johngian**
* Create a read-only pool to the replica node
* Always default to master node
* Implement routing for read/write queries

### CODE REVIEW

**Comment by johngian** [comment]
Thanks @phirework for the feedback!

**Comment by johngian** [comment]
Heads up: this needs a config change in the deployment

**Comment by phirework** [comment]
LGTM. Does @The-smooth-operator need to be involved for the deployment change?

**Comment by johngian** [comment]
Yes, this needs some config entries in our setup. @The-smooth-operator how do we handle this ?

**Comment by The-smooth-operator** [comment]
@phirework sorry I have missed the first comment. @johngian what we need here is a read only replica of the master DB right?

**Comment by The-smooth-operator** [comment]
At the moment this is blocked by not having a read only replica database. I'll be working in adding the database soon.

**Comment by The-smooth-operator** [comment]
The read replica was there. Working with nemo for next steps

**Comment by phirework** [comment]
Since the env vars PR got merged, can we come back to this ticket again?

**Comment by johngian** [comment]
I think after that change, its safe to merge it without affecting the nubis setup:
https://github.com/mozilla/voice-web/pull/2542/files#diff-4b440fd57875e4e560d22fdd1f5706e2R69

**Comment by johngian** [comment]
@phirework thoughts? Other than that I am ok to merge it

**Comment by phirework** [comment]
Looks great, thanks! Can you work with Alberto to get this up on Dev so we can test it for as long as possible before the next release?

**Pull request merged**
