### PR TITLE
Fix localisation

### PR DESCRIPTION
**Pull request by jonorthwash**
Changing "terms" (≈terminology) to "terms" ("and conditions").

### CODE REVIEW

**Comment by phirework** [comment]
Hi @jonorthwash, localization is handled through Pontoon, so all changes have to go through there. Otherwise, your changes here will just get overwritten next time we sync from Pontoon anyway. Please make your changes there: https://pontoon.mozilla.org/ky/common-voice/web/locales/en/messages.ftl/?search=terms&string=175937

**Comment by jonorthwash** [comment]
@phirework, I added the correct translation there 2 weeks ago (you can see it at the URL you sent), but nothing has changed, which is why I tried a PR.  Could you clarify how data from Pontoon gets incorporated in?

**Comment by phirework** [comment]
@jonorthwash It looks like your translation has not been reviewed yet, perhaps one of the manager of the KY instance can help here? https://pontoon.mozilla.org/ky/contributors/

**Comment by jonorthwash** [comment]
It doesn't look like either of the `kir` managers has done anything in over a year.  Is there a way for me to become a manager or reviewer or something of the sort?

**Comment by phirework** [comment]
@nukeador @peiying2 any insight into what's involved here?

**Comment by jonorthwash** [comment]
@JRMeyer

**Comment by JRMeyer** [comment]
@jonorthwash - Chorobek is one of the managers, you should ping him to get approval

**Comment by peiying2** [comment]
@jonorthwash Let me send an email to the managers and cc you to it.

**Pull request closed without merging**
