### PR TITLE
Consolidate resources in a single account.

### PR DESCRIPTION
**Pull request by The-smooth-operator**
These recourse were created in a separated AWS account. Now that Gregor is steppping out, we want to have everything in the same account

### CODE REVIEW

**Comment by The-smooth-operator** [comment]
@Gregoor before we run this through Gozer, can you please have a quick sanity check?
If working as expected, this changes will create:
 - 2 S3 buckets
 - 1 t2.small EC2 instance in the same VPC where the DB runs.

**Comment by The-smooth-operator** [comment]
Hey @gozer can you please take a look if this looks good?

**Comment by MichaelKohler** [comment]
What's the status on this one?

**Comment by The-smooth-operator** [comment]
I'd say this one is deprecated. I'm going to talk to Gregor for clarifying if we have something to do, in that case I'll open a new PR.

**Pull request closed without merging**
