### PR TITLE
2019-12-07 Sentence Collector Export

### PR DESCRIPTION
**Pull request by MichaelKohler**

### CODE REVIEW

**Comment by MichaelKohler** [comment]
@nukeador r?

**Comment by MichaelKohler** [comment]
(no change in locales needed)

**Comment by mozillakab** [comment]
@dabinat  @MichaelKohler 

Someone to merge? We need the kab sentences.

As I'm seeing more involved languages, I think we need more  exports/week

**Comment by nukeador** [comment]
@MichaelKohler I see a travis fail here, so I assume it's not safe to merge. Can you check?

@mozillakab We are doing weekly exports, and basically we rely on Michael free time to do it, we don't really have the bandwidth to do more exports per week, I hope you understand.

Cheers.

**Comment by MichaelKohler** [comment]
> @MichaelKohler I see a travis fail here, so I assume it's not safe to merge. Can you check?

That is unrelated

**Comment by nukeador** [comment]
Ok, thanks!

**Pull request merged**
