### PR TITLE
Designate and upgrade devDependencies

### PR DESCRIPTION
**Pull request by rileyjshaw**
I'm working on updating some of our dependencies. This is Step 1, where
I move everything that probably won't break the live site into
devDependencies, then upgrade them wholesale with `ncu -u --dep=dev`.

Package upgrades in this diff:

**/**
```
 concurrently   ^4.1.1  →   ^5.0.0
 husky          ^3.0.2  →   ^3.1.0
 prettier      ^1.18.2  →  ^1.19.1
 pretty-quick  ^1.11.1  →   ^2.0.1
 typescript      3.7.2  →    3.7.3
```

**/server**
```
 @types/jest                    ^24.0.16  →   ^24.0.23
 @types/mkdirp                    ^0.5.1  →     ^0.5.2
 jest-matcher-utils              ^24.8.0  →    ^24.9.0
 jest                            ^24.8.0  →    ^24.9.0
 newrelic                        ^5.10.0  →     ^6.2.0
 nodemon                         ^1.19.1  →     ^2.0.1
 source-map-support              ^0.5.12  →    ^0.5.16
 ts-jest                          24.0.2  →     24.2.0
 tsc-watch                        ^2.2.1  →     ^4.0.0
 typescript                        3.7.2  →      3.7.3
```

**/web**
```
 @babel/core         ^7.6.4  →   ^7.7.4
 @babel/preset-env   ^7.6.3  →   ^7.7.4
 @sentry/browser     ^5.5.0  →  ^5.10.1
 @types/webpack     ^4.39.3  →  ^4.41.0
 chalk               ^2.4.2  →   ^3.0.0
 concurrently        ^4.1.1  →   ^5.0.0
 css-loader          ^3.2.0  →   ^3.2.1
 file-loader         ^4.2.0  →   ^5.0.2
 husky               ^3.0.2  →   ^3.1.0
 postcss-nested      ^4.1.2  →   ^4.2.1
 react-dev-utils     ^9.0.1  →  ^10.0.0
 style-loader        ^1.0.0  →   ^1.0.1
 typescript           3.7.2  →    3.7.3
 webpack-cli         ^3.3.9  →  ^3.3.10
```

Test plan:

- `yarn install`
- Deleted all generated files
- `yarn build`
- `yarn prettier`
- `yarn test`
- `docker-compose up`

**Please checkout this commit with `hub pr checkout`, then through a version of this test plan on your own.**
Try to break something! 😈

### CODE REVIEW

**Comment by rileyjshaw** [comment]
Note: `yarn prettier` will cause a few changes to our code. I'm leaving those out to declutter the commit, I'll add the code changes in a follow-on diff once this lands.

**Comment by rileyjshaw** [comment]
Home now, but I'll look into the Travis failures tomorrow!

**Comment by rileyjshaw** [comment]
`The engine "node" is incompatible with this module. Expected version ">= 10.13.0"`

**Comment by rileyjshaw** [comment]
Waiting on https://github.com/mozilla/voice-web/pull/2455. Will rebase once that's landed.

**Comment by rileyjshaw** [comment]
Just rebased on #2455 so we can test it against Node v10.

**Comment by rileyjshaw** [comment]
CI errors should stop once https://github.com/mozilla/voice-web/pull/2465 lands.

**Comment by rileyjshaw** [comment]
@phirework rebased and fixed the image loader! Should be ready for re-review :)

**Comment by phirework** [comment]
Looks good to me!

**Pull request merged**
