### PR TITLE
Add "Czech Republic English" accent to user.ts

### PR DESCRIPTION
**Pull request by jhutar**
When I'm recording English phrases, I'm pretty sure I should not be considered as any of the currently listed accents.

### CODE REVIEW

**Comment by Omniscimus** [comment]
Hi, is English spoken somewhere in the Czech republic as a first language? If not, it probably shouldn't be in the list of accents. The information on the website is currently a little unclear about this. See also issue #242.

**Comment by mikehenrty** [comment]
Thanks for the report @jhutar!

@kdavis-mozilla any thoughts about this? is it a dupe of #242?

**Comment by kdavis-mozilla** [comment]
@mikehenrty I'd see it as a dupe of #242 

@jhutar Do you think #242 captures your concerns?

**Comment by jhutar** [comment]
I'm sorry for not responding earlier. Yes, this is basically duplicate of #242.

**Pull request closed without merging**
