### PR TITLE
Spanish accents (from EN wikipedia)

### PR DESCRIPTION
**Pull request by nukeador**
Spanish accents from https://en.wikipedia.org/wiki/Spanish_dialects_and_varieties#Sets_of_variants

### CODE REVIEW

**Comment by capiscuas** [comment]
The East Spain accents are missing, also galician.
https://en.wikipedia.org/wiki/File:Spanish_dialects_in_Spain-en.png

I would add as:
    estepeninsular: 'España: Este peninsular (Baleares, Cataluña, Comunidad Valenciana)',
    galicia: 'España: Galicia'

**Comment by nukeador** [comment]
The original article didn't include them as accents but as separate languages (Galician and Catalan)

> In purple, the major variations and dialects of Castilian/Spanish in Spain.
In other colors, the extent of the other languages of Spain in the bilingual areas.

**Comment by capiscuas** [comment]
Yeah but people who don't speak those languages or those languages(Catalan and Galician) are not their mother tongue, they should still be able to choose Castillian/Spanish and their region(Galicia) for example.

I am not a linguistic but I think that it makes sense for bi-lingual regions or bi-lingual countries.

**Comment by capiscuas** [comment]
It is interesting issue.
image

In my case Catalan and Castilian/Spanish are my 2 mother tongues: in Catalan I can select Valencia(my dialect), but in the case of Castilian I can't choose my area(East Spain) cause it only shows dialects of regions non-bilingual. 
Should I then just select Catalan->Valencia?

What if somebody lives in valencia but only speaks Castilian?

**Comment by nukeador** [comment]
Maybe we should include all regions in one of the existing buckets?

Galicia and Catalonia in the Northern and Valencia in the Central?

**Comment by capiscuas** [comment]
Galicia is rather Northern
and Catalonia, Valencia and Baleares(islands) are rather Eastern(new bucket, bcs our accents are influenced by the fact that most of us are native-bilingual)

**Pull request merged**
