### PR TITLE
Remove 6100 sentences from English wiki dump

### PR DESCRIPTION
**Pull request by dabinat**
Stats:
Total sentences: 1342646
Successful sentences: 1336486
Failed sentences: 6160
foreign term: 6122
missing word: 26
length: 7
partial sentence: 2
punctuation: 2
duplicate sentence: 1

CC @nukeador

### CODE REVIEW

**Comment by nukeador** [comment]
Can you past a few examples on the changes on "failed sentences" and "foreign term"? I can't see the full diff from here and I see there are 57 additions, can you add them also here to check?

Thanks!

**Comment by dabinat** [comment]
Here are some examples of sentences with foreign words:

> In Blackfoot, the name for the site is "Estipah-skikikini-kots".
> Thus, "Sprechgesang" is often merely a German alternative to "recitative".
> Cao Xueqin, still a young child, lived in poverty with his family.
> Dahut and most inhabitants of Ys were worshippers of Celtic gods.
> Mazar was born in Ciechanowiec, Poland, then part of the Russian Empire.
> A person from Glenelg is known in Gaelic as an "Eilgeach".
> She was the star of hit films including "Taegukgi" and "The Scarlet Letter".
> The neighborhood encompasses three "grunnkrets": Strandkaien, Torgalmenningen, and Vaskerelven.
> The international school "Satchidananda Jothi Niketan" is located in Mettupalyam, Tamil Nadu.
> In German it is called "Tatzenkreuz" from "Tatze", foot, paw.
> Abitibi-Baie-James-Nunavik-Eeyou contains more than half of Quebec's total landmass.
> Flowers currently is the executive officer, or "Yrmin-Drighten", of the Rune-Gild.
> Necklaces called "colaq" were also worn and made using similar items to the "onguaghachik".

Examples of scientific terms:

> Acetyl-CoA carboxylase catalyzes the production of malonyl-CoA from acetyl-CoA.
> HgCdTe and PtSi are materials with similar use.
> "Amapasaurus tetradactylus" has four digits, and the lizards of the genus "Leposoma" have five.
> Neither is a synonym of "Agaricus subrufescens".
> Species include "Hancea integrifolia".
> The edible frog "Pelophylax" kl.
> Malonyl-CoA is formed by carboxylating acetyl-CoA using the enzyme acetyl-CoA carboxylase.
> "Casuarina equisetifolia" trees and Coconut palms fringe the coast.
> It had a straighter neck than "Oxydactylus" or "Aepycamelus".

Also, just to clarify, no new sentences were added - the ones marked as additions are sentences that were modified to either expand abbreviations or correct spelling mistakes.

**Comment by nukeador** [comment]
Thanks for this. I can't remember if we talked about how to integrate this clean-up directly into the wiki-scrapper, but it would be really useful. If we don't have an issue there is this something you are interested in owning?

**Comment by dabinat** [comment]
@nukeador I don’t know Rust but I can probably figure out how to do it. But I was planning to make those changes once I have my filter script in a good place. There’s still a lot more to filter out. My goal is to get it to the point where flagging up a sentence is a relatively rare occurrence.

**Comment by MichaelKohler** [comment]
> I don’t know Rust but I can probably figure out how to do it.

If there is already a rule type that fits your need, you don't need to know Rust. If there isn't, please create an issue in the scraper repo and we can see what we can do :)

**Pull request merged**
