### PR TITLE
Create hocine-corpus6

### PR DESCRIPTION
**Pull request by belkacem77**
New Kabyle sentences
Corpus from Hocine Benamar published under CC0.
From https://github.com/Hociben/corpus-kabyle
Gathered 4 files: corpus10, corpus11, corpus12,corpus13
100 sentences in each file: total 400 sentences

### CODE REVIEW

**Comment by belkacem77** [comment]
Hi @mikehenrty 
Please, if you can or someone who has irght to merge mu pulls it would be nice. I exposed and corrected some errors.
We are going to work on the first kab model (generation and test: TTS and Deep Speech) within next months.

I'd like know when we discover some errors and the recordings are correct, are we going to lose these recordings?

**Comment by Gregoor** [comment]
Hey @belkacem77, that would be me. (best to also ping me directly in the future, though I also get notifications for every activity in this repo)

RE corrections: No recordings are deleted, the incorrect sentence is just deactivated so that no new recordings can be created for it.

**Comment by Hociben** [comment]
Thanks Muḥend.

**Comment by belkacem77** [comment]
@Hociben  thanks for your corpus

**Comment by Hociben** [comment]
@belkacem77 lplease I have 300 more sentences.

**Comment by belkacem77** [comment]
@Hociben ok I will PR them later

**Comment by Hociben** [comment]
@belkacem77 Ok thanks for all what you are doing

**Pull request merged**
