### PR TITLE
List of sentences for Esperanto (eo)

### PR DESCRIPTION
**Pull request by bidaian**
These are some of the sentences (less than 10 words) from the "Fundamenta Krestomatio de la Lingvo Esperanto" (https://www.gutenberg.org/files/8224/8224-h/8224-h.htm)

### CODE REVIEW

**Comment by mikehenrty** [comment]
awesome thanks for curating these sentences @bidaian !

**Comment by RobinvanderVliet** [comment]
There are some sentences in this file with parentheses. Are those appropriate for this project? How should people pronounce them?

**Comment by bidaian** [comment]
Hi, we are cleaning up the big batch with the 5k sentences. You can actually delete the whole file since it's going to be sent again with the new texts.

**Comment by mikehenrty** [comment]
ok @bidaian, let's delete this file in the PR with the new sentences. thanks for your work!

**Comment by RobinvanderVliet** [comment]
> Hi, we are cleaning up the big batch with the 5k sentences. You can actually delete the whole file since it's going to be sent again with the new texts.

@bidaian Is there any news on this big batch?

**Pull request merged**
