### PR TITLE
Czech Europarl dataset

### PR DESCRIPTION
**Pull request by Adrijaned**
Created a dataset of sentences from the v7 EuroParl dataset. Sentences included are all 10 words or shorter, following steps were taken while creating the file:
```bash
grep -v "[:()]" europarl-v7.cs-en.cs > europarl-v7.cs-en.cs2            # remove special symbols
sort -u europarl-v7.cs-en.cs2 > europarl-v7.cs-en.01                    # remove duplicates
grep -v "[0123456789]" europarl-v7.cs-en.01 > europarl-v7.cs-en.02      # remove numbers
awk "NF<=10" europarl-v7.cs-en.03 > europarl-v7.cs-en.04                # remove everything longer than 10 words
grep -v ",^" europarl-v7.cs-en.04 > europarl-v7.cs-en.05                # This was a typo, but effectively NOP
grep -v "\.\.\." europarl-v7.cs-en.05 > europarl-v7.cs-en.06            # remove ellipsis
grep -v ",$" europarl-v7.cs-en.06 > europarl-v7.cs-en.07                # remove everything with trailing comma
grep "^[A-ZÁČĎĚÉÍŇÓŘŠŤÚÝŽ]" europarl-v7.cs-en.07 > europarl-v7.cs-en.08 # sentences must start with uppercase
grep -v "[\"\-\']" europarl-v7.cs-en.08 > europarl-v7.cs-en.09          # remove some more special symbols
grep -v "[A-Z][A-Z]" europarl-v7.cs-en.09 > europarl-v7.cs-en.10        # remove abbreviations
grep -v "\. " europarl-v7.cs-en.10 > europarl-v7.cs-en.11               # remove periods not at the end of line (abbreviations)
grep -v " -" europarl-v7.cs-en.11 > europarl-v7.cs-en.12                # remove dashes preceded by space - often was sounding unnatural
grep -v "[^.\!?]$" europarl-v7.cs-en.12 > europarl-v7.cs-en.13          # check all sentences end with .?!
grep -v "[ßüÜ]" europarl-v7.cs-en.13 > europarl-v7.cs-en.14             # remove some common special symbols
cat europarl-v7.cs-en.14 | awk 'length<102' > europarl-v7.cs-en.15      # just for sanity, check length
```
Step from 02 to 03 was just manually removing some extra junk that was all sorted to the front of the file

Here is the link to GDoc for QA: https://docs.google.com/spreadsheets/d/1XvkdlIJIH311Y0GLuzz4_Z09bfN1spRq4BDRCFGiRBQ/edit?usp=sharing

A total of  98908 sentences has been extracted. The file has then been`shuf`ed, and 4000 first sentences manually reviewed. The review discovered about 2.2% of sentences to contain hard to pronounce names, and another roughly .9% of sentences to contain typos or other problems. Additional 2.3% of sentences were then found to contain names that are easily pronounceable in Czech, and thus were not considered a problem. In the latest commit, a lot of names was also removed irrespective of their pronounceability; this was not reflected in the review, i.e. the review was done on the version of data from the first commit.

### CODE REVIEW

**Comment by stefangrotz** [comment]
> 10 words or shorter

Normally, the sentences must be 14 words or less. Did you choose 10 words to keep the sentences simpler and shorter? If yes, interesting idea for this corpus with many complicated sentences.

**Comment by Adrijaned** [comment]
To be fair, I chose 10 words just to be on the safe side, plus I wasn't exactly sure what the required limit is. Especially when you may encounter such "words" as "french-english-german" (single word), that may take 2 seconds to pronounce alone.

**Comment by Adrijaned** [comment]
QA hopefully finished, I fixed a few of the more common issues I noticed, and also removed everything beginning with `Pan[í]` as those commonly contained problematic names. (equivalent of english "Mr."/"Mrs.")
@nukeador

**Comment by nukeador** [comment]
Thanks for this work. Is it possible to update the first comment to include all the information that we requested for the German version here?

https://github.com/mozilla/voice-web/pull/2539#issue-365521747

Thanks!

**Comment by Adrijaned** [comment]
I found a more reasonable way to grep for names, so I redid the last commit (the previous version caught a lot of non-name sentences and on the other hand, left a lot more names in). Also, I hopefully included included everything relevant in the first comment, let me know if there is still something missing.

**Comment by nukeador** [comment]
Looks good. A final question, do we know why German was able to get 379K sentences and this one is only 98K?

Also, for naming consistency, can we name the file europarl-v7-cs.txt ?

Thanks!

**Comment by Adrijaned** [comment]
I'm quite certain that the difference in the amount of sentences is only due to the amount of sentences in the original dataset (670 000 sentences for czech vs 2 200 000 sentences for german)

Renamed.

**Comment by nukeador** [comment]
Oh, makes sense. Merging this now, as I commented on discourse I would be cool if we can document this process and tools for other languages :-)

**Pull request merged**
