### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by rileyjshaw**
The big change in this PR is that we're upgrading React / React DOM from v16.8 -> v16.12. Unrelated / minor changes are broken into separate commits.

There are no breaking changes in this version of React, but I clicked around to ensure there were no obvious breakages. I paid special attention to API changes / deprecations detailed in https://github.com/facebook/react/blob/master/CHANGELOG.md.

Remember: you may need to kill existing Docker processes / images to ensure dependency updates happen within `docker compose`.

### CODE REVIEW

**Comment by phirework** [comment]
😍 will review this today, thank you!

**Comment by phirework** [comment]
In doing a brand new docker build, here are the warnings I get (other log statements ommitted): 

```
[2/5] Resolving packages...
warning Resolution field "@types/react@16.8.19" is incompatible with requested version "@types/react@^16.9.17"
[3/5] Fetching packages...
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
...
[4/5] Linking dependencies...
warning "workspace-aggregator-d94d9385-7d3b-4737-9cc7-401f29cc5af1 > server > db-migrate-plugin-typescript@2.0.0" has unmet peer dependency "ts-node@^3.3.0".```

Only the first one looks directly related to this, and seems to be a `yarn.lock` issue? Otherwise this looks good. As long as we don't merge into staging we can test this on the dev environment and see how things go.

**Comment by rileyjshaw** [comment]
Thanks for testing @phirework, and sorry to have missed that. I'm back in the office now. I just fixed the dependency resolution issue with https://github.com/mozilla/voice-web/pull/2512/commits/1aeb5a7a3b3f4e5c008029bb0fe78933091fc74b, so I think this is finally good to go.

**Comment by phirework** [comment]
You're the best, thanks!

**Pull request merged**
