### PR TITLE
Adding Dutch sentences extracted from EuroParl

### PR DESCRIPTION
**Pull request by FremyCompany**
All these sentences have already been approved for German. Indeed, these sentences should a strict subset of the sentences added from German EuroParl in #2539, because I applied some additional filtering to avoid all proper names, and only keep sentences of a certain length. 

This file was generated using the command:
```
cat ./europarl-v7.nl-en.nl |
awk 'length<102' |
grep -P '^[A-Z]' |
grep -P '[.?!…] *$' |
grep -v -P '[A-Z][.][A-Z]' |
grep -v -P '.[A-Z]' |
grep -v -P '[0-9]' |
grep -P '[a-z][a-z][a-z]' |
sed -r 's/  +/ /g' |
awk 'length>25' |
awk 'NF<=14' | 
sed -r 's/ ?'"'"' s /'"'"'s /g' |
sort | uniq | shuf | less
```

I already reviewed thousands of these sentences back when I proposed to add them a couple of months ago, so I am quite confident these can be added now, especially with additional filtering in place, and the wide review of the German sentences (which are translation of these sentences).

More sentences could be added if I removed the restriction on abbreviation and capital letters (proper names) but I feel like this isn't necessary at this point. I'd rather have the proper names come from the Wikipedia extractor, where they should be more balanced across categories.

### CODE REVIEW

**Comment by FremyCompany** [comment]
Extract from the file, so people can review without having to look at the entire file:

<details><summary>250 first lines of the file</summary><div>

```
Het is heel leuk om hem hier te zien.
Dankzij onze druk werd hij in vrijheid gesteld.
Een aantal rechters en advocaten zit nog steeds in de gevangenis.
Dat alles gaan we dus eerst in alle rust doen.
Ik zal alle wettelijke middelen aangrijpen die tot mijn beschikking staan.
Er zijn krachtige maatregelen tegen het terrorisme nodig.
Voor het eerst wordt een grenswaarde voor een kankerverwekkende stof vastgelegd.
We weten dat dit een heel gevoelig en oud probleem is.
Uw doel is het verder verbeteren van het zevende kaderprogramma.
Uiteraard moeten we in de toekomst geleidelijk te werk gaan.
De rechtsgrondslag van de verordening is gewijzigd van interne markt naar milieu.
Frontex is de oplossing niet.
Waarom is dit verslag belangrijk?
Voor zover ik weet, hebben ze dat nu ook allemaal gedaan.
Daarom hebben we het verslag verworpen.
Enkele sprekers van de verschillende fracties hebben reeds op dit probleem gewezen.
Waarom hebben soortgelijke conferenties tot nu toe niets opgeleverd?
Er staan vele conclusies in het verslag die mij wezensvreemd zijn.
Raadsvoorzitter zijn is waarschijnlijk de voornaamste ambt die ik ooit zal bekleden.
Daarom zien wij uit naar het werk van het instituut voor gendergelijkheid.
Anders heeft ons werk hier geen zin.
De wetgevende macht moet de uitvoerende macht in alle vrijheid kunnen controleren.
Zoals ik al zei: het was een verzoek om verdediging van de parlementaire immuniteit.
Ik wil slechts twee voorbeelden noemen.
Dat komt heel zeker ook het toerisme ten goede.
De term "nationalisme" wordt overigens niet in de tekst genoemd.
Uit deze workshops is duidelijk dat de huidige crisis niet cyclisch maar structureel is.
Dit is reeds te merken aan de besparingen in de openbare sector.
Helaas hebben sommige clausules die nog steeds in de verordening staan juist dat effect.
We moeten ook de discriminatie die inheemse en boerenvrouwen ondergaan, erkennen en ertegen vechten.
Als u dat niet had gedaan, zouden we hier waarschijnlijk nog steeds zijn.
De noodhulp moet in de gewijzigde en aanvullende begroting tot uitdrukking komen.
Patenten dienen ter bescherming van innovatie, niet ter onderdrukking van concurrentie.
Op de tweede plaats moeten we iets doen aan de congestie.
Deze voorstellen strandden op de kwestie van de medezeggenschap.
Zo werkt het systeem in alle andere verbanden ook.
Socialezekerheidsstelsels gaan daar niet altijd even flexibel mee om.
Dat brengt mij bij de schrikbeelden.
Hartelijk dank, en iedereen een prettige kerst.
Dat is eenvoudiger, minder ingewikkeld.
Voor het eerst zijn ook sociale aspecten opgenomen.
Wij mogen geen compromissen sluiten als het om veiligheid gaat.
Er is aparte wetgeving voor detergentia en voor cosmetica, en zo hoort het ook.
Het is een onrechtvaardige wet en een schandvlek.
Vanzelfsprekend moeten wij alles vanuit een mondiaal perspectief doen.
Om deze doelstelling te verwezenlijken, is efficiëntere samenwerking onontbeerlijk.
Dit jaar zal zij een aanbeveling inzake mediageletterdheid publiceren.
We kunnen ook veel meer doen wat de externe dimensie betreft.
Ten eerste dient meer ruchtbaarheid te worden gegeven aan het website-adres.
We hebben een fonds nodig om hen te hulp te komen.
Ik ben hier heel cynisch over.
Wijziging van de maximumkredietbedragen zou tot veel administratieve rompslomp hebben geleid.
Er moet onderzoek worden gedaan naar herbebossing.
We moeten het gewoon blijven proberen.
Ik probeer de afgevaardigden, dus ook u, altijd ter wille te zijn.
Wij hebben een betrouwbaar resultaat nodig.
Tenslotte worden in het verslag discriminatie en sociale uitsluiting besproken.
De vraag is daarom niet zozeer of de richtlijn ideaal is of niet.
Dit besluit wordt door ons gesteund.
Ons voorbehoud bij een aantal andere amendementen komt voort uit een aantal overwegingen.
Ik hoop dat de geachte collega's deze amendementen zullen verwerpen.
Doe er wat aan en snel graag!
Voor de uitwerking van een grondwet is samenwerking vereist tussen alle politieke krachten.
We hebben een stokje gestoken voor de zogenaamde 'master-feederstructuren'.
Ik ben blij dat elf van mijn twaalf amendementen door de commissie zijn goedgekeurd.
Dat is wachten op de problemen.
Ik hoef u nauwelijks te vertellen naar welke kant mijn politieke fractie neigt.
Onze sancties zijn niet effectief.
Ik herhaal het nog eens, mijnheer de commissaris: het is wetenschappelijk niet bewezen.
Mensen met meer gezag dan ikzelf hebben zich hierover krachtig uitgesproken.
Omdat dit de enige kans is dat er in de regio weer hoop gloort.
Bovendien is er veel vraag naar meer veiligheid voor zulke betaalmiddelen als kredietkaarten.
Zo werkt het in een parlement: wie het laatst spreekt heeft dikwijls gelijk.
Veel collega' s zijn zich daar helaas nog niet in voldoende mate van bewust.
Dat is mijn persoonlijke ervaring, voor wat het waard is.
Bureaucratie en ingewikkelde regelgeving moeten tot een minimum worden beperkt.
Wij zijn het er ook over eens dat wij nú resultaten moeten boeken.
De komende decennia zal de wereld iets aan het klimaatprobleem moeten doen.
Zonder democratie kan er geen gerechtigheid bestaan.
Als we ergens behoefte aan hebben, dan zijn dat daden.
Indien de parallelle invoer uit derde landen wordt toegestaan, dalen de prijzen van merkartikelen.
Dit zijn allemaal vragen waarop we als commissie antwoorden willen.
Daarvoor wens ik haar te feliciteren.
Wij moeten een einde maken aan de rechtsonzekerheid binnen de industrie.
Wij zullen uw opmerkingen uiteraard overbrengen.
Ik dring er bij de commissaris op aan dat wel te doen.
Er hebben zich allerlei soorten problemen voorgedaan.
Volgens mij komt dat reeds naar behoren in de overwegingen tot uitdrukking.
De democratische overgang is dus in gang gezet.
Bezuinigen betekent niet gewoon korten, maar vooral de beschikbare middelen zinvol gebruiken.
Voorts begrijp ik uw bezorgdheid over het mogelijke risico van koolstoflekken.
Wij erkennen dat uw onafhankelijkheid niet onbeperkt is.
Daarom is het belangrijk om altijd beide aspecten in het oog te houden.
Daarom moeten we deze organisaties steunen.
Eerdere subsidies moeten dientengevolge worden teruggevorderd.
Er moet nog het een en ander worden ondernomen op economisch en bestuurlijk vlak.
Vandaag is er goede hoop op beide fronten.
Auteursrecht is een persoonlijkheidsrecht, een recht van erkenning en identificatie.
Wij willen tot de kern van deze onderhandelingen doordringen.
Wij hebben dat altijd gezegd.
Zij hoeven geen schuld of schaamte te voelen.
Die centrale bank kan dat dus rechtvaardigen, ook naar buiten toe.
Ik geef u enkele redenen waarom wij ons zorgen maken.
We zullen samen stappen nemen om deze digitale kloof te overbruggen.
Dat is misbruik van overheidsgeld.
De tweede tegenstrijdigheid heeft te maken met de inkomsten.
Hoe zit het met de dialoog tussen theïstische, niet-theïstische en atheïstische gelovigen?
Dat is het punt waarom het gaat: bestrijding moet op decentraal niveau plaatsvinden.
Gaat u het voortdurende beleid van inkrimping, dat de landbouwsector is opgelegd, herzien?
We moeten waarnemers sturen met een brede opdracht.
Dit project is slecht voorbereid.
Dit is dus allemaal heel positief.
Laten we eindelijk een eind maken aan deze handel met de dood.
Wij hebben steun nodig voor een verstandige en pijnloze herstructurering van het platteland.
Nergens zijn er meer tienermoeders en besmette baby's.
Als men de regeling op die manier bekijkt, begrijpt men het beleid echter verkeerd.
Ten tweede de veiligheid rond vliegvelden.
Onderneem eindelijk eens actie!
Deze stoffen hebben een lange levensduur en bioaccumulatieve eigenschappen.
Dat is de beste manier om vooruitgang te boeken.
Dat blijkt uit de lage opkomst bij de verkiezingen.
Om af te ronden wil ik u een verhaal vertellen.
Het hadden ook mijn kinderen kunnen zijn.
Wij stemmen nu over het verzoek tot urgentverklaring.
Ik hoop dan ook dat deze vergissing wordt hersteld.
Na een aantal maanden wordt de bank zenuwachtig.
Toch hebben we een belangrijke slag verloren.
Dit is inderdaad een bijzonder omstreden vraagstuk.
Ik denk dat de tijd rijp is voor concrete initiatieven.
Dit zijn enkele redenen waarom wij niet voor het verslag kunnen stemmen.
Deze ontwikkeling is extra goed merkbaar in de nieuwe lidstaten.
Het kan de dieren helemaal niets schelen in wat voor val ze creperen.
Mijn laatste punt betreft de periode van zes weken.
Laten we deze onschuldige slachtoffers in elk geval gedenken.
Ik dank u voor uw aandacht, en geniet van uw banaan!
Ik zie op dit moment twee fundamentele met dit proces samenhangende problemen.
De vorige richtlijn is niet goed omgezet.
We zijn beiden zelfstandige partners in de samenwerking.
En ik zal u vertellen waarom niet.
Deze kwestie roept een aantal vragen op.
Ik denk bijvoorbeeld aan de akkoorden inzake de scheepsbouw.
Voor geïmporteerde producten is dit evenwel niet altijd het geval.
Eurojust moet onafhankelijk kunnen werken.
Wij durven, waarde collega's het te hebben over een politiek model.
Deze beschuldiging van moord is gebaseerd op gerechtelijke documenten die geen standhouden.
Om eerlijk te zijn geloof ik dat zij in dit opzicht heeft gefaald.
De regeringen hebben om allerlei redenen hun kandidaten voorgedragen.
Een derde van deze tabak is van zeer lage kwaliteit en wordt zelden gerookt.
Dat doen wij niet, aangezien we in een psychopathisch bewind geen vertrouwen kunnen stellen.
Ik wil nogmaals iedereen bedanken die hierbij geholpen heeft.
Het is gebeurd op de manier zoals we het hebben vastgelegd.
Bovendien is er gezorgd voor slagvaardigheid.
Ons gemeenschappelijk visserijbeleid moet worden hervormd.
Ik denk dat we daar veel uit kunnen leren.
Ik vind dat moeilijk te geloven.
Er moeten meer projecten komen die door verschillende ministeries tegelijk gedragen worden.
Dat wil er bij mij niet in!
Die richtlijn zal tegelijkertijd met de euro van start gaan.
Beide komen uit de sociaal-democratie en zijn niet bereid uw voorstellen te accepteren.
Dit tijdperk zal echter spoedig aflopen.
Houdt men er misschien rekening mee dat het een of andere schip zinkt?
Nationale en bilaterale wetgeving moet daarop worden afgestemd, evenals bepaalde bestaande rechten.
De andere verbeteringen in de tekst rechtvaardigen nochtans goedkeuring van het eindverslag.
Er worden enorm veel aanvallen op de fysieke infrastructuur gepleegd.
In mijn land wordt dat “iemand om de tuin leiden” genoemd.
Wij willen antwoorden op deze vragen.
Mijn tweede opmerking is dat het verslag van dit jaar heel evenwichtig is.
Wat ik zeg is alles behalve radicaal.
Het verlenen van humanitaire hulp zou daardoor heel wat gemakkelijker worden.
We hadden op uw steun gehoopt, commissaris.
Het is niet aan mij om het financiële aspect van sport streng te veroordelen.
Dan tot slot nog twee overwegingen.
Uiteindelijk zijn het deze procedures die beslissen of een politiek systeem legitiem is.
Naar mijn mening is het niet voldoende dat we globaal over duurzame ontwikkeling praten.
Concurrentie is slechts concurrentie als ze op gelijke voet gebeurt.
Grootse en strategische investeringen in de landen van herkomst zijn noodzakelijk.
Ik verzoek u vriendelijk de nagedachtenis van deze mensen te eerbiedigen.
Hoe wordt de oorsprong specifiek aangeduid?
Aan de andere kant moeten trainingsnetwerken in die richting worden ontwikkeld.
Wij moeten zorgvuldig controleren hoe deze richtlijn ten uitvoer wordt gelegd.
Het is uitstekend werk, van grote kwaliteit, en daar wil ik hem voor bedanken.
We stemmen dan ook tegen dit verslag.
Wij nemen niet deel aan deze stemming.
De tijd was te kort om alle onderhandelingen tot een goed einde te brengen.
Zij heeft samen met u over dit dossier onderhandeld, en was ook heel tevreden.
Ze vergroten ook het risico van armoede voor vrouwen, vooral in eenoudergezinnen.
De internationale gemeenschap moet deze schendingen een halt toeroepen.
Ik moedig de agentschappen vanzelfsprekend aan dit voorbeeld te volgen.
Ik zal u vertellen wat wij in het kader van de toetredingsonderhandelingen kunnen doen.
Ik zal ook op deze tweede kwestie een antwoord trachten te formuleren.
Dat is het probleem waar het om draait.
Nu duiden wij samen enkele prioriteiten en enkele havens aan.
Als woorden niet door daden worden gevolgd blijven ze loos.
Zo staat dat inderdaad ook voor mij opgeschreven.
Daarna wordt een elektronische reisvergunning verstrekt.
Dat mogen we niet toestaan.
Datgene wat volgens mij misschien het belangrijkste is, is de gebrekkige chemische veiligheid.
Het kaderbesluit gaat ook vergezeld van een uitbreiding van de procedurele rechten van mensen.
We zijn verantwoordelijk voor het goede financiële beheer van de communautaire financiën.
Ten tweede: de duidelijkheid van de regelgeving.
De effecten waarover we het hier hebben zijn dus zeer ernstig.
Van drie dingen ben ik overtuigd.
Vermoedelijk is het economische idiotie.
Hoewel we doelstellingen definiëren zijn deze niet bindend.
Laten wij wel een beetje consequent zijn.
We zullen controleren of een strengere reglementering noodzakelijk is.
Op alle niveaus moeten wij die nieuwe geesteshouding aannemen.
Ik wil een aantal punten in mijn verslag speciaal onder uw aandacht brengen.
Volgens ons kunnen wij zonder hun medewerking geen milieubeleid voeren.
Aan de orde is de voortzetting van het debat over vrouwenhandel.
De nieuwe wetgeving houdt in dat spoormaatschappijen meer verantwoordelijkheid op zich moeten nemen.
Hoe dan ook, ik heb het van tevoren gevraagd en u had tijd genoeg.
Wij sociaal-democraten eisen ook sociale en ecologische duurzaamheid.
Wij zijn vrouwen, echtgenotes en moeders.
Kunt u daar een uitspraak over doen?
Ik wou dat ik u dat duidelijk kon maken.
Ik hoop dat alle lidstaten dit standpunt zullen willen steunen.
Uit studies blijkt overduidelijk dat de mensen best meer geld willen uitgeven.
Het probleem is dat deze dochtermaatschappijen afzonderlijke rechtspersonen zijn.
Blijkbaar wordt hierover in de officiële berichtgeving met geen woord gerept.
En daarvan hebben wij allemaal voordeel.
Ik zou het derhalve op prijs stellen als u daaraan vasthield.
De sancties zijn bovendien getrapt, wat heel belangrijk is.
De probleemstellingen rond een verslag dienen binnen de parlementaire commissie te worden behandeld.
De top moet eigenlijk zelfs ‘onthutsend’ worden genoemd.
Dit optreden moet echter zichtbaar en vastberaden zijn.
Misschien zou u kunnen bevestigen dat u dezelfde mening bent toegedaan.
Derhalve kan dit verslag op mijn steun rekenen.
Voor de belangenvertegenwoordigers liggen er glorievolle dagen in het verschiet.
Als er dingen mis gaan, moeten zij worden gecorrigeerd.
Ik ben heel tevreden dat de wijzigingen begrotingsneutraal zijn.
Over het oorsprongslandprincipe kan ik kort zijn.
Wie zal opdraaien voor de gevolgen van dit enorme risico?
Dit verslag is daarvan het ondubbelzinnige bewijs.
Administratief kunnen er veel struikelblokken worden weggeruimd.
Er is onder de lidstaten geen meerderheid om dit te veranderen.
Het is financieel een uiterst goed renderende investering.
Echte cultuur is niet afhankelijk van voorschriften of een eindeloze stroom subsidies.
Verder is het noodzakelijk dat het systeem in de praktijk bruikbaar is.
Het is immers niet mogelijk dat dat iets aan de juridische werkelijkheid verandert.
Verder wil ik aandacht vragen voor de distributieproblematiek.
In de tweede plaats hebben wij een dialoog gevoerd met de sociale partners.
Nu zouden ze ineens niet meer tegen een dergelijke concurrentie op kunnen boksen.
We moeten dus anders gaan denken over auto's en ze anders gaan gebruiken.
Vrouwensport is heel goed, maar het is daarom nog geen fundamenteel recht.
Wij zullen tot maandag moeten wachten om te kunnen vaststellen hoeveel daarvan succesvol zijn.
Vrijstelling en bescherming zijn de twee kernideeën.
Ik wil u niets eens zeggen dat deze positieve stimulansen niet werken.
Die is er gekomen, maar is nog niet goed genoeg.
Immigratie kan niet alleen als een veiligheidskwestie worden gezien.
De situatie wordt alleen maar slechter, niet beter.
```

</div></details>

**Comment by FremyCompany** [comment]
Hi, can we please get this merged?

With the quarantine, there are efforts getting more people to contribute their voice, and those efforts are seriously less useful for Dutch if we don't add more sentences...

**Comment by FremyCompany** [comment]
cc @phirework @nukeador

**Comment by sroet** [comment]
quick comments about the top 250:

>Veel collega' s zijn zich daar helaas nog niet in voldoende mate van bewust.

a space after an `'` is not common in NL and wrong in this sentence, I am not to familiar with the `grep` and `sed` commands, so I don't know what the origin of this typo is.

> We hebben een stokje gestoken voor de zogenaamde 'master-feederstructuren'.

It looks like stuff within quotations can be a result of "dutchified" English, which is debatable to label as proper Dutch. However, this is an inherent problem of the language; as modern technical terms are getting rarer in Dutch and we commonly default to the English (or these dutchified English) terms instead (at least in my field of (theoretical) chemistry).

Other than these I did not see any issues in the top 250 and it if the origin of the typo is fixed it should be suitable to merge

**Comment by nukeador** [comment]
Hello,

We would need a QA report with the same information it was provided for the German case in their first comment.

https://github.com/mozilla/voice-web/pull/2539

Feel free to use the same spreadsheet template to document the QA review.

Thanks!

**Comment by FremyCompany** [comment]
> quick comments about the top 250:
> 
> > Veel collega' s zijn zich daar helaas nog niet in voldoende mate van bewust.
> 
> a space after an `'` is not common in NL and wrong in this sentence, I am not to familiar with the `grep` and `sed` commands, so I don't know what the origin of this typo is.

Good catch! It's actually written that way in the original file, not sure why. 

I already had a rule to fix this (`sed -r 's/ ?'"'"' s /'"'"'s /g' |`) but sounds like it didn't catch everything, I'll take a look at this.

> > We hebben een stokje gestoken voor de zogenaamde 'master-feederstructuren'.
> 
> It looks like stuff within quotations can be a result of "dutchified" English, which is debatable to label as proper Dutch. However, this is an inherent problem of the language; as modern technical terms are getting rarer in Dutch and we commonly default to the English (or these dutchified English) terms instead (at least in my field of (theoretical) chemistry).

It doesn't seem very frequent, but I guess I could remove all sentences with words between such quotes to remove all things that weren't translatable to Dutch, as those words are quite unlikely to be used again in a normal conversation. That should be very few sentences in total.

> Other than these I did not see any issues in the top 250 and it if the origin of the typo is fixed it should be suitable to merge

**Comment by FremyCompany** [comment]
I made a review spreadsheet for the first 4000 sentences of the file:
[Link to the review spreadsheet](https://1drv.ms/x/s!AhVrPgyThAkTgRVcgxmjzoOXVrBZ?e=pNG5jn)

Since I'm under quarantine it should be easy to spend some time to review them.

**Comment by FremyCompany** [comment]
After reviewing 500 new sentences, the results are as follow:

> # Score: | 98.60% | Done: | 12.50%
> 
> OK? | Count | Reason
> -- | -- | --
> ✔ | 493
> ❌ | 7
> ...  | 5 | strong opinion
> ... | 1 | English words
> ...  | 1 | typo

Happy to wait until someone else can take a look at more of these sentences, but I think the results are well within expectations

**Comment by FremyCompany** [comment]
With 1000 sentences reviewed:


> # Score: | 98.80% | Done: | 25.03%
> 
> OK? | Count | Reason
> -- | -- | --
> ✔ | 989
> ❌ | 12
> ...  | 6 | strong opinion
> ... | 3 | English words
> ...  | 2 | typo
> ... | 1 | difficult to say

**Comment by FremyCompany** [comment]
With 1000 sentences reviewed:

> # Score: | 98.60% | Done: | 50.00%
> 
> OK? | Count | Reason
> -- | -- | --
> ✔ | 1972
> ❌ | 28
> ...  | 11 | strong opinion
> ... | 11 | English words
> ...  | 4 | typo
> ... | 2 | difficult to say

I truly don't see any reason not to merge at this point.

**Comment by nukeador** [comment]
@mention me when the QA has been finished and we have a comment with all the information we can review. We want to stick to our QA guidelines and apply it to every source to ensure the same quality level.

I would advise to get more people to help with the review.

Thanks!

**Comment by stefangrotz** [comment]
Hey, a little feedback at this point since I have also gone through this with the German import: it is really hard to get people to do this kind of work. German was stuck at 2000 reviewed sentences for quite long and it was only luck, that one motivated person came by and reviewed the other 2000 sentences in just one night. I understand that you want to lift the quality and the 300-500 sentences that we checked for the Wikipedia imports were indeed too little. But if you would accept 2000 sentences instead of 4000 this would really make things easier, especially for smaller languages. You will likely have this discussion at every import from now on if you stick to this practice.

**Comment by nukeador** [comment]
I understand where this frustration is coming from. But we also need to understand that this is a very substantial addition to our text corpus, that's why we have a very clear QA process, to reduce the risk introduced, which grows bigger when the corpus to be added is bigger.

What I'm hearing is that getting people to help with the review is hard. Let's focus on that and work with the rest of the community to come up with tips on how to get this.

I would suggest to open a discourse topic about this blocker and an ask for people to provide feedback on how to get more people to help. I'm sure others can chime in to support.

Thanks for your understanding!

**Comment by stefangrotz** [comment]
Okay, I understand that. It would be great to have a way to shout out to a part of the community for help. The old language mailinglists have been ideal, but no one seems to use them any more. But let's have this discussion somewhere else.

**Comment by FremyCompany** [comment]
Just a quick note about the current status and why this stalled.

After reviewing 2000 sentences I don't think it makes any sense for me to review any more of them. There is absolutely no information gain to expect from that.

On the other hand, I got two lovely people to accept to review 1000 sentences each, to get us to the 4000 limit. One of them, a native Dutch speaker who happens to also teach Dutch in secondary school, reviewed the sentences numbered 3000 to 4000, getting us 75% on the way there. The other person didn't follow through, and I felt bad getting someone else to do it initially, since someone else already had committed and just claimed to be busy.

I guess that was a mistake but, at the same time, with the lockdown being mostly lifted now in both Belgium and the Netherlands, there is significantly less value in getting this done in a the immediate future and so I haven't put much effort in recruiting someone else to get the review done. I have my own work activities to worry about, especially as productivity hasn't been ideal over the course of the last month, as you would expect.

In addition, given the 1000 sentences reviewed by a Dutch teacher didn't move the numbers in a significant way, I agree with @stefangrotz that this seems to be a rather pointless number-crunching exercise. So if that must be done then I will get to it eventually, but I am no longer in a rush.

**Comment by FremyCompany** [comment]
Here are the stats after 1k additional sentences have been reviewed by a Dutch teacher:
> # Score: | 98.17% | Done: | 75.08%
>
> OK? | Count | Reason
> -- | -- | --
> ✔ | 2948
> ❌ | 55
> ...  | 13 | strong opinion
> ... | 15 | English words
> ...  | 23 | typo
> ... | 4 | difficult to say

**Comment by sroet** [comment]
I had some time left today, and reviewed the last 1000
 
# Score: | 98.23% | Done: | 100%
| OK? | Count | Reason |
|-------|---------|-------------|
| yes  | 3929 | |
| no   |    71| |   
| ... | 19| English words|
| ... | 14| strong opinion |
| ... | 25| typo |
| ... | 12 | difficult to say |
| ... | 1 | abbreviation |

@nukeador the QA is finished

**Comment by FremyCompany** [comment]
Cool, thank you @sroet!

Before merging, I would like to see if there's any additional filter I can implement to reduce the percentage of bad case even further. One idea I have in mind is to reject sentences using words that are not in a dictionary of Dutch words. That is quite likely to catch most of the "typo" and "English words" sections, which cover most of the issues detected.

I will try to work on this during the weekend so @nukeador can merge either the current version or the updated version on Monday, depending on which has the best issue ratio on the 4000 reviewed sentences.

**Comment by sroet** [comment]
please also strip out any sentences that have the word "ecu" (which is the one abbreviation that went through), as it might be common in this data set (it means "European Currency Unit")

**Comment by applied-machinelearning** [comment]
Perhaps an additional step could be to pipe the list through hunspell / nuspell with:
 `hunspell -d nl_NL -L -G` ?

**Comment by FremyCompany** [comment]
I had my own dictionary of Dutch words from a news corpus, and filtering out all sentences that did have a word not in its top 250k vocabulary resulted in 33 errors for 3513 lines. 

I then ran hunspell and it resulted in 35 errors for 3864 lines.

Based on that, I uploaded the hunspell version of the filter, because it filtered less things out while having about the same error/total ratio; the second advantage being that anybody can run this filter locally without having to download my dictionary.

The final set consists in 250 000 sentences.

The final review stats are:
> # Score: | 99.10% | Done: | 100.0%
>
> OK? | Count | Reason
> -- | -- | --
> ✔ | 3864
> ❌ | 35
> ...  | 13 | strong opinion
> ... | 4 | English words
> ...  | 7 | typo
> ... | 11 | difficult to say

I think this is now ready to be merged. Thank you everyone! // cc @nukeador

**Comment by nukeador** [comment]
Thanks so much for this fantastic work!

I'm going to merge and then rename the file to a simpler one to avoid potential issues.

It would be great if at some point you can share the the rest of the community over discourse the process and tips & tricks to get their language europal corpus included.

Thanks again!

**Comment by Fjoerfoks** [comment]
For the next opportunity, please consider to invite other Dutch people to help out. I didn't know people were working on this, so it would have helped if e.g. @nukeador pointed other Dutch people to this discussion.
Or should we put these kind of discussions up on Discourse under a specific Dutch topic, what do you all think?
Anyway, great accomplishment!
Don't know if anyone else has been working on the Wiki-scraper, but I have. Now that I have Frisian almost ready I plan to work on Dutch too, which might come up with another 250k sentences. The check with Hunspell is interesting, will take a look.

**Pull request merged**
