### PR TITLE
Add Esperanto Wiki scrape

### PR DESCRIPTION
**Pull request by MichaelKohler**
Export: 132521 sentences
Deduped: 102959 sentences

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Here's the full export file, in case you want to check if the dedupe is correct. 
[wiki.eo.txt](https://github.com/mozilla/voice-web/files/4008322/wiki.eo.txt)

@stefangrotz does this look good to you?

**Comment by stefangrotz** [comment]
Hi, thanks for the scrape! I found many doubled sentences in the dedupe, something must have gone wrong. Did you sort it alphabetically before you deleted duplicates? I recommend using:

> sort -u wiki.eo.txt > wiki.eo.dedup.txt

**Comment by stefangrotz** [comment]
Hi @MichaelKohler thanks for the scrape! The dedupe looks good to me, I get the same numbers when I run a simple "sort -u".

**Comment by MichaelKohler** [comment]
Just a quick note here, if we merge these sentences would probably already end up on the website. I guess I'm fine with that but I would also be happy to merge PRs against my branch so they show up here.

**Comment by stefangrotz** [comment]
Good point, I will do a PR with some basic removals before this goes live.

**Comment by MichaelKohler** [comment]
I sent you an invite to my fork, feel free to push directly to the branch so it shows up in this PR. 

https://github.com/MichaelKohler/voice-web/tree/feature/eo-wiki

**Comment by stefangrotz** [comment]
Hey I pushed my changes, I don't really understand why it says 45k additions now. The file now hase 100 628 sentences, I think this is enough for an initial cleanup.

**Comment by MichaelKohler** [comment]
Will have a look tomorrow. Thanks!

**Comment by stefangrotz** [comment]
I used my dedupe file, maybe the order is a little different.

**Comment by stefangrotz** [comment]
Third commit deletes some asiatic signs and replaces some unusual space signs with the normal space.

**Comment by MichaelKohler** [comment]
Did a quick check to review this, in total there were 66 sentences in this PR that do not appear in my file. 64 of those I could review through the PR, and those were not found by my script as you did the spacing improvements. The following two sentences I could not identify in the original file, I haven't done any transformation for searching them though. Can you tell me where those come from?

```
Por mi tiu baza afero estis la sendependeco de Pollando.
Ĉefa urbo dee ĝi estis Nitro, Kastelo de Nitro.
```

The rest looks good to me :)

**Comment by MichaelKohler** [comment]
Oh, looks like the first one is an encoding issue, I've found the following in the original file:

```
Ĉefa urbo dee ĝi estis Nitro, Kastelo de Nitro.
```

The second one is a fixed sentence, to remove the quote:

```
Por mi tiu baza afero estis la sendependeco de Pollando".
```

So all good.

**Comment by MichaelKohler** [comment]
@phirework this can be merged if you have time :)

**Comment by stefangrotz** [comment]
Thanks, strange. I will look into this later this evening. How did you create your dedup? Could they have gone lost there?

**Comment by phirework** [comment]
Thanks for all the hard work you two!

**Comment by stefangrotz** [comment]
Thanks for all your support too you two :)

**Pull request merged**
