### PR TITLE
Create popular-language1.txt

### PR DESCRIPTION
**Pull request by mozillakab**
popular language.
Source: https://github.com/mozillakab/corpus-kab/blob/master/popular-language.txt
License: CC0

### CODE REVIEW

**Comment by mozillakab** [comment]
@nukeador Hi again.

The kab team is very involved with Common Voice. So some of them are requesting the tool (I talked about it on our FB pages: Common Voice s Teqbaylit), so if the tool is ready enough, we would like use it now. It's not easy at all to manage the corpus since I'm the one who ca make Pull Request (decision of  the ka team to avoid dupplication and minimize errors).

**Comment by mozillakab** [comment]
@Gregoor , I sent them via sentence-collector. Should I close this PR?

**Comment by Gregoor** [comment]
That's great, thanks for that! This can be closed then indeed.

**Comment by nukeador** [comment]
Hey, please, hold on.

As we inform over slack today we are currently cleaning up the database, your sentences will be removed. We plan to launch the beta today, please wait for the announcement in a few.

Thanks!

**Pull request closed without merging**
