### PR TITLE
First 10k sentences for Estonian

### PR DESCRIPTION
**Pull request by sander85**
This commit adds 10k sentences for Estonian language.

### CODE REVIEW

**Comment by fishel** [comment]
Can we go ahead with this? Anxious to start collecting data :-)

**Comment by LRSaunders** [comment]
We are currently working on a sentence uploading tool that will pull these sentences into common voice and hope to have it up and running mid December.

**Comment by JRMeyer** [comment]
ping to @LRSaunders and @Gregoor, can we activate Estonian, please? :smiley_cat:

**Comment by Gregoor** [comment]
Sure. Did someone proof-read these? Then I'll merge and activate 🚀

**Comment by fishel** [comment]
Localization is already merged, waiting for the data to go live

**Comment by Gregoor** [comment]
@fishel so someone checked these sentences were alright? Just want to make that we're not starting off with incorrect sentences.

**Comment by fishel** [comment]
Not the whole 10k manually, but by random sampling it looked ok.

**Comment by Gregoor** [comment]
Alrighty, let's see how far this takes us :)

**Comment by Gregoor** [comment]
Note, that just because it's merged, doesn't mean it's live yet. I'll be on a plane soon, so probably won't get to deploy before tomorrow.

**Pull request merged**
