### PR TITLE
bundle server typescript compile

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

**Comment by mikehenrty** [comment]
@nevik or @kenrick95, I'm having trouble bundling server code using the TS compiler. Can either of you take a look at this and tell me what I'm doing wrong?

**Comment by kenrick95** [comment]
Hmm the bigger question should be: why bundle into one file?

**Comment by mikehenrty** [comment]
> Hmm the bigger question should be: why bundle into one file?

Slightly faster, slightly cleaner, and I don't have to worry about duplicates js files for every ts file when doing fuzzy search working locally.

**Comment by mikehenrty** [comment]
Let's close this for now as it's not worth the effort investigating right now.

**Pull request closed without merging**
