### PR TITLE
Re-do proper Assemblee Nationale extraction

### PR DESCRIPTION
**Pull request by lissyx**
for f in $(wc -l data/debats-assemblee-nationale/*.txt | sort -nr | head -n 100 | grep txt | awk '{ print $2 }');
do
	F=$(basename `echo $f`);
	T="assemblee-nationale_$F";
	tail -n 1200 $f | head -n 40 > $T;
done;

### CODE REVIEW

**Comment by lissyx** [comment]
Ok, this might benefit from new improvements soon, so let's not merge it yet.

**Comment by lissyx** [comment]
@mikehenrty Should be better to merge now

**Comment by mikehenrty** [comment]
@lissyx looking good to me! shall I merge it?

**Comment by lissyx** [comment]
yes, merge all the things!

**Pull request merged**
