### PR TITLE
List of deleted / added sentences

### LINKED ISSUE #2259: Invalid french accents in sentence collector data
We got a report of "words cut" being displayed (likely a font rendering issue). Further investigation lead to unexpected french `é` character: `é`.

A quick check on the data reveals:
```
$ git grep -c "é" server/data/fr/
server/data/fr/sentence-collector.json:1
server/data/fr/sentence-collector.txt:50800
```

### PR DESCRIPTION
**Pull request by lissyx**
Fixes #2259

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Can you remove the _deleted one again? We should only have sentences to add in this part of the repo. Also, why is the "added" file more lines than deleted?

**Comment by lissyx** [comment]
@MichaelKohler What's the status here ?

**Comment by lissyx** [comment]
> Given that this adds 76k sentences, and only 62k had been approved through Sentence Collector, I don't think we can merge this. See [#2259 (comment)](https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487).

Can't we just identify the extra ones added ? Is there anything I need to do here ? @MichaelKohler

**Comment by MichaelKohler** [comment]
The additional ones need to go through the Sentence Collector. You can find the sentences that were found in the sentence collector at https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487.

**Comment by lissyx** [comment]
> The additional ones need to go through the Sentence Collector. You can find the sentences that were found in the sentence collector at [#2259 (comment)](https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487).

You're not addressing my queston: do you need me do to the split of those extra, non-sentence-collector-validated sentences ? Are you taking care of it ?

**Comment by MichaelKohler** [comment]
I'm not, no.

**Comment by lissyx** [comment]
@MichaelKohler Is there anyone working on that ? Do I have to do anything ?

**Comment by MichaelKohler** [comment]
> @MichaelKohler Is there anyone working on that ? Do I have to do anything ?

That is something to check with the French community. I have no idea why those were not initially submitted. As far as I know, there is nobody working on that.

**Comment by lissyx** [comment]
> > @MichaelKohler Is there anyone working on that ? Do I have to do anything ?
> 
> That is something to check with the French community. I have no idea why those were not initially submitted. As far as I know, there is nobody working on that.

As I said somewhere else, this importer was submitted by a community member, but then I have not overviewed the submission to Sentence Collector.

Yet, in the end, « French community », it means I have to take care of it. So what are the remaining steps N

**Comment by MichaelKohler** [comment]
> Yet, in the end, « French community », it means I have to take care of it. So what are the remaining steps ?

Identification of which sentences were never submitted, and then adding them through https://common-voice.github.io/sentence-collector/#/add

**Comment by lissyx** [comment]
```
import unicodedata
import difflib

added   = open('server/data/fr/issue_2259_added.txt').readlines()
deleted = open('server/data/fr/issue_2259_deleted.txt').readlines()

def to_nfkc(l):
    nfkc = []
    for e in l:
        s = unicodedata.normalize("NFKC", e)
        s = s.strip()
        nfkc.append(s)
    return nfkc

added   = to_nfkc(added)
deleted = to_nfkc(deleted)

for a in added:
    if not(a in deleted):
        print('{}'.format(a))
```

**Comment by lissyx** [comment]
[issue_2259_missing.txt](https://github.com/mozilla/voice-web/files/3837653/issue_2259_missing.txt)

@MichaelKohler This was generated with the script above. It covers a bit more of sentences, is it fine for you ?

**Comment by lissyx** [comment]
> > Yet, in the end, « French community », it means I have to take care of it. So what are the remaining steps ?
> 
> Identification of which sentences were never submitted, and then adding them through https://common-voice.github.io/sentence-collector/#/add

What is the status of the other sentences ? Have they been added ?

**Comment by MichaelKohler** [comment]
> @MichaelKohler This was generated with the script above. It covers a bit more of sentences, is it fine for you ?

Compared to what? The list should be around 12k sentences, see https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487. Only ~62k were ever added to the sentence collector. Your file in this PR here has  ~74k. So if you compare the file which has the deletions from Sentence Collector (https://github.com/mozilla/voice-web/files/3790958/removed_sc.txt) with your file in this PR here, you should get the right amount. These will be the sentences that you have in the other repo, but were never added to Sentence Collector.

> > > Yet, in the end, « French community », it means I have to take care of it. So what are the remaining steps ?
> > 
> > 
> > Identification of which sentences were never submitted, and then adding them through https://common-voice.github.io/sentence-collector/#/add
> 
> What is the status of the other sentences ? Have they been added ?

Which ones? I didn't add any sentences. The sentences that need to be added to the Sentence Collector would be the ones from the diff that would result from the steps above. So around 12k.

**Comment by lissyx** [comment]
@MichaelKohler I'm trying to understand the status here, but nothing is clear.

**Comment by MichaelKohler** [comment]
Can you tell me what is not clear about https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487?

Additionally to that comment there, there is the issue here that your diffs adds way too many sentences. Only 62k get removed from the export, but you add 74k. The difference of 12k needs to be added through the Sentence Collector to go through the approval process. Does that make sense?

**Comment by lissyx** [comment]
> Can you tell me what is not clear about [#2259 (comment)](https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487)?

What is not clear is what those `removed_*.txt` files do represent, what has been done since I shared the lists.



> The difference of 12k needs to be added through the Sentence Collector to go through the approval process. Does that make sense?

Thank you, I'm not totally dumb, I understand that we can't add data that has not been validated.

**Comment by lissyx** [comment]
@MichaelKohler Also, you document differences of 413 lines, but I still cannot figure out where you get that number from. So on one side, you say there is a delta of 413, on the other, 12k (more 13k, if I'm looking at the proper files).

**Comment by MichaelKohler** [comment]
> > Can you tell me what is not clear about [#2259 (comment)](https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487)?
> 
> What is not clear is what those `removed_*.txt` files do represent, what has been done since I shared the lists.

* You shared deleted.txt
* I took deleted.txt and searched for all matching sentences in the Sentence Collector
* This results in removed_sc.txt - these are the ones that were found in the sentence collector -> ~62k
* Everything in removed_export.txt would get removed from https://github.com/mozilla/voice-web/blob/master/server/data/fr/sentence-collector.txt
* This leads to a difference of 413 sentences, as explained in the comment further down, that were added to the Sentence Collector but were never approved, therefore are not found in the export at https://github.com/mozilla/voice-web/blob/master/server/data/fr/sentence-collector.txt

There are two different issues:
* https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487 which leads to the difference of 413 
* This PR here that adds ~12k more sentences

**Comment by MichaelKohler** [comment]
And the difference of 413 needs to be calculated, but let's not discuss this here, let's do that over in https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487. What needs to be done here is adding the ~12k to the Sentence Collector and remove them from your file here, so that your added file only includes corrected sentences that have been wrong in the Sentence Collector.

**Comment by lissyx** [comment]
>     * [](https://github.com/mozilla/voice-web/blob/master/server/data/fr/sentence-collector.txt)
> 
> 
> There are two different issues:
> 
>     * [#2259 (comment)](https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487) which leads to the difference of 413
> 
>     * This PR here that adds ~12k more sentences

So, since the begining we are not talking about the same thing ...

**Comment by lissyx** [comment]
@MichaelKohler So you need that I remove from `server/data/fr/issue_2259_added.txt` the strings that are not in `removed_sc.txt` ?

**Comment by MichaelKohler** [comment]
Correct.

**Comment by lissyx** [comment]
```
#!/usr/bin/python3

import unicodedata
import difflib

added   = open('server/data/fr/issue_2259_added.txt').readlines()
deleted = open('removed_sc.txt').readlines()

def to_nfkc(l):
    nfkc = []
    for e in l:
        s = unicodedata.normalize("NFKC", e)
        s = s.strip()
        nfkc.append(s)
    return nfkc

added   = to_nfkc(added)
deleted = to_nfkc(deleted)

not_new = []
new = []
for a in added:
    if not(a in deleted):
        new.append(a)
    else:
        not_new.append(a)

print('new', len(new))
print('not_new', len(not_new))

with open('server/data/fr/issue_2259_added_fixed.txt', 'w') as f:
    f.write('\n'.join(not_new))

with open('server/data/fr/issue_2259_added_push-to-sc.txt', 'w') as f:
    f.write('\n'.join(new))
```

**Comment by lissyx** [comment]
@MichaelKohler Re-pushed, with two files. How does it looks to you ?

**Comment by MichaelKohler** [comment]
Oh, damn, sorry my fault. You would need to compare against https://github.com/mozilla/voice-web/files/3790960/removed_export.txt and not the SC one. Sorry, got confused there. Then you should end up with 62842 corrected sentences which corresponds to the amount that will get deleted through the export.

**Comment by MichaelKohler** [comment]
This will then leave us with the remaining 413 sentences (as mentioned at https://github.com/mozilla/voice-web/issues/2259#issuecomment-548096487) that were in SC but were never approved, and I will take care of those once we're ready.

**Comment by lissyx** [comment]
> Oh, damn, sorry my fault. You would need to compare against https://github.com/mozilla/voice-web/files/3790960/removed_export.txt and not the SC one. Sorry, got confused there. Then you should end up with 62842 corrected sentences which corresponds to the amount that will get deleted through the export.

Nope. I get this ~63k amount when using `removed_sc.txt`, but if I use `removed_export.txt`, I'm getting 47k.

**Comment by MichaelKohler** [comment]
Yeah, I can't figure out that discrepancy. However, that's not a big deal.

# Re-adding sentences that will get removed through the export

I'm suggesting to go down the following route:

* We take removed_export.txt and correct those sentences
* Once we figured out how we can correct sentences without losing speech data for it (to be figured out over in #2259) we run the export on the Sentence Collector side - this will delete data in https://github.com/mozilla/voice-web/blob/master/server/data/fr/sentence-collector.txt
* We add the corrected sentences again (see first point here) - this here is the PR for that.

Here's my try on having those sentences corrected. @lissyx can you confirm that these have the correct encoding? If so, can you please update this PR with those sentences?

[issue2259_deleted_export_readd_fixed.txt](https://github.com/mozilla/voice-web/files/3843186/issue2259_deleted_export_readd_fixed.txt)

I've adapted your script and used the following:

```
#!/usr/bin/python3

import unicodedata
import difflib

export_removed   = open('removed_export.txt').readlines()

def to_nfkc(l):
    nfkc = []
    for e in l:
        s = unicodedata.normalize("NFKC", e)
        s = s.strip()
        nfkc.append(s)
    return nfkc

export_removed_fixed   = to_nfkc(export_removed)

for s in export_removed_fixed:
    print('{}'.format(s))
```

With this we can at least make sure that we're not deleting sentences that are not getting re-added again and we therefore lose sentences.

# Sentences that were never in Sentence Collector

Then we have sentences that are in the French repository, but are not in Sentence Collector. For those I would then suggest to do the following:

@lissyx or any other French contributor add the sentences from the French repo that are not in the `issue2259_deleted_export_readd_fixed.txt` file above to the Sentence Collector for approval. The Sentence Collector seems to have some issues regarding duplication detection. So it would be great if you could de-dupe them once you have the final list before adding them to be sure we don't add duplicate sentences. It's not a big deal if there are duplicates, as the export seems to dedupe correctly. But this would lead to more work for reviewers than necessary.

Do you agree with that approach?

**Comment by lissyx** [comment]
>  @lissyx can you confirm that these have the correct encoding?

Checking with some accents, it looks right.

**Comment by lissyx** [comment]
> @lissyx or any other French contributor add the sentences from the French repo that are not in the `issue2259_deleted_export_readd_fixed.txt` file above to the Sentence Collector for approval.

Just to be clear because I'm getting kinda lost, against which file should this be computed ?

**Comment by lissyx** [comment]
> If so, can you please update this PR with those sentences?

@MichaelKohler  I've added your file and updated the PR

**Comment by MichaelKohler** [comment]
> > If so, can you please update this PR with those sentences?
> 
> @MichaelKohler I've added your file and updated the PR

Thanks, can you remove the two other files so this would be ready to merge once the tasks in #2259 are done?

> > @lissyx or any other French contributor add the sentences from the French repo that are not in the `issue2259_deleted_export_readd_fixed.txt` file above to the Sentence Collector for approval.
> 
> Just to be clear because I'm getting kinda lost, against which file should this be computed ?

Against `issue2259_deleted_export_readd_fixed.txt` which you included in this PR now. Bonus points if you do some cleanup if there are patterns of obviously wrong sentences, as that would decrease the amount of work needed to have them reviewed in Sentence Collector.

**Comment by lissyx** [comment]
> Thanks, can you remove the two other files so this would be ready to merge once the tasks in #2259 are done?

Done and PR updated



> Against `issue2259_deleted_export_readd_fixed.txt` which you included in this PR now. Bonus points if you do some cleanup if there are patterns of obviously wrong sentences, as that would decrease the amount of work needed to have them reviewed in Sentence Collector.

Sure. Do you need that now ? In this PR or in another ?

**Comment by MichaelKohler** [comment]
> > Against `issue2259_deleted_export_readd_fixed.txt` which you included in this PR now. Bonus points if you do some cleanup if there are patterns of obviously wrong sentences, as that would decrease the amount of work needed to have them reviewed in Sentence Collector.
> 
> Sure. Do you need that now ? In this PR or in another ?

No no, this is about the sentences that would need to go through the Sentence Collector, this can't be done through this PR here. And in terms of timing, I don't see any urgency with that, I just think it would be a shame to have sentences in a repo somewhere, but those not being on track to get towards voice.mozilla.org in any way :)

**Comment by lissyx** [comment]
> And in terms of timing, I don't see any urgency with that, I just think it would be a shame to have sentences in a repo somewhere, but those not being on track to get towards voice.mozilla.org in any way :)

We are on the same page here. I read too fast I guess and missed the fact that you want me to push the delta to Sentence Collector.

So, just to be clear, what needs to go into Sentence Collector is the difference between `issue2259_deleted_export_readd_fixed.txt` and `removed_sc.txt` ?

**Comment by MichaelKohler** [comment]
> So, just to be clear, what needs to go into Sentence Collector is the difference between `issue2259_deleted_export_readd_fixed.txt` and `removed_sc.txt` ?

No. Any sentences that you had in your initial deletion list that are not in `issue2259_deleted_export_readd_fixed.txt`. Preferably with no dupes inside that difference so the Sentence Collector doesn't need t shout at you :)

**Comment by lissyx** [comment]
> > So, just to be clear, what needs to go into Sentence Collector is the difference between `issue2259_deleted_export_readd_fixed.txt` and `removed_sc.txt` ?
> 
> No. Any sentences that you had in your initial deletion list that are not in `issue2259_deleted_export_readd_fixed.txt`. Preferably with no dupes inside that difference so the Sentence Collector doesn't need t shout at you :)

So diff between `issue2259_deleted_export_readd_fixed.txt` and `issue_2259_deleted.txt` then, I think?

**Comment by lissyx** [comment]
So, comparing `issue2259_deleted_export_readd_fixed.txt` and `issue_2259_deleted.txt` I get ~29k sentence. Does that sounds about right ?

**Comment by lissyx** [comment]
```
   29239 server/data/fr/issue_2259_added_push-to-sc_sorted_uniq.txt
   29391 server/data/fr/issue_2259_added_push-to-sc.txt
```

**Comment by MichaelKohler** [comment]
Ah, quick note that probably will help: the exported sentences go through a cleanup, so the `issue2259_deleted_export_readd_fixed.txt` might include such transformations and therefore might not map directly against your `issue_2259_deleted.txt` file. Can you check against the following?

* No transformation applied
* Transformation from https://github.com/Common-Voice/sentence-collector/blob/master/shared/cleanup/languages/en.js applied

If none of those are found, then the sentence most probably hasn't been in the Sentence Collector yet. If I interprete this correctly this should be the difference between these two files, which AFAICR is around 12k.

**Comment by lissyx** [comment]
> Transformation from https://github.com/Common-Voice/sentence-collector/blob/master/shared/cleanup/languages/en.js applied

Some of those transformations are plain wrong for french typography, only those should make sense
```
      .replace('  ', ' ')
      .replace(/^,+\s/, '') // we do not want commas at the beginning of the sentence
      .replace(/^,+/, '') // we do not want commas at the beginning of the sentence
      .replace(/,+$/, '') // we do not want commas at the end of the sentence
```

**Comment by MichaelKohler** [comment]
That's out of scope here. Happy to take a PR for a specific FR cleanup file, see https://github.com/Common-Voice/sentence-collector/blob/master/shared/cleanup/CLEANUP.md for more info.

**Comment by lissyx** [comment]
> That's out of scope here. Happy to take a PR for a specific FR cleanup file, see https://github.com/Common-Voice/sentence-collector/blob/master/shared/cleanup/CLEANUP.md for more info.

You are missing my point: if you generated your text file using that, then this is just wrong.

**Comment by lissyx** [comment]
> That's out of scope here.

It is in plain scope. I don't understand when this code is applied. Was it applied for all french sentences ? Did you just used it in this case ?

**Comment by MichaelKohler** [comment]
So, first of all I created an issue regarding the cleanup script not being correct for French: https://github.com/Common-Voice/sentence-collector/issues/268

Then I noticed a crucial bug in the cleanup script, which we will take care of, but let's do that after we have finished our work here. Otherwise this is gonna end up in a full mess: https://github.com/Common-Voice/sentence-collector/issues/269

Let's tackle everything step by step:

* Let's wait for a response from the CV team regarding not invalidating already recorded sentences
* Then let's add https://github.com/Common-Voice/sentence-collector/issues/268
* And fix https://github.com/Common-Voice/sentence-collector/issues/269
* And finally apply the same mechanism for not invalidating recorded hours

Now, for your issue at hand here. This is how the export currently works, be it bug free or not, that's what we need to deal with. This means that the sentences in `issue2259_deleted_export_readd_fixed.txt` have this transformation applied. This changes the steps for you to:

* Take all sentences of `issue_2259_deleted.txt`
* Apply the transformation of https://github.com/Common-Voice/sentence-collector/blob/master/shared/cleanup/languages/en.js
* Check the transformed sentences against `issue2259_deleted_export_readd_fixed.txt`
* If the sentence doesn't exist in `issue2259_deleted_export_readd_fixed.txt` then add it to the Sentence Collector as a new sentence

I will take care of everything apart from adding new sentences to the Sentence Collector.

Feel free to ping me in Slack if you want a sync conversation.

**Comment by lissyx** [comment]
Thanks @MichaelKohler, looks like a mess. Last time I checked this cleanup process code-wise, it was (a long time ago and) not applied to french. Or those rules were not there.

Anyway, thanks for the followup issues. I'll work and fix the current sentences wrt the potential bugs as soon as possible (unlikely today though).

**Comment by lissyx** [comment]
>     * Apply the transformation of https://github.com/Common-Voice/sentence-collector/blob/master/shared/cleanup/languages/en.js (by only replacing the _first_ occurence for the replaces that do not use regex)

Inded, doing this gets me to 15k sentences:
```
$ wc -l server/data/fr/issue_2259_added_push-to-sc*
  15446 server/data/fr/issue_2259_added_push-to-sc_sorted_uniq.txt
  15491 server/data/fr/issue_2259_added_push-to-sc.txt
```

**Comment by lissyx** [comment]
> * Take all sentences of `issue_2259_deleted.txt`
> 
> * Apply the transformation of https://github.com/Common-Voice/sentence-collector/blob/master/shared/cleanup/languages/en.js (by only replacing the _first_ occurence for the replaces that do not use regex)
> 
> * Check the transformed sentences against `issue2259_deleted_export_readd_fixed.txt`
> 
> * If the sentence doesn't exist in `issue2259_deleted_export_readd_fixed.txt` then add it to the Sentence Collector as a new sentence

I've re-worked on that, ensuring I apply the same transformations.
I end up with those two lists for performing the comparison:
```
$ diff -uw server/data/fr/issue_2259_deleted_MOD.txt server/data/fr/issue2259_deleted_export_readd_fixed_MOD.txt |diffstat
 issue2259_deleted_export_readd_fixed_MOD.txt |14029 ---------------------------
 1 file changed, 1 insertion(+), 14028 deletions(-)
```

There were some discrepencies due to differently-replaced spaces before punctuations, so I performed the comparison by getting rid of all spaces.

This provides me with 13k sentences:
```
   13621 server/data/fr/issue_2259_added_push-to-sc.txt
```

**Comment by lissyx** [comment]
```
#!/usr/bin/python3

import unicodedata
import re
import csv
import difflib

deleted              = open('server/data/fr/issue_2259_deleted.txt').readlines()
deleted_orig         = open('server/data/fr/issue_2259_deleted.txt').readlines()
deleted_export_readd = open('server/data/fr/issue2259_deleted_export_readd_fixed.txt').readlines()

def save_as(fname, d):
    with open(fname, 'w') as f:
        f.write('\n'.join(d))

def to_nfkc(l, cleanup=True):
    nfkc = []
    for e in l:
        s = unicodedata.normalize("NFKC", e)
        s = s.strip()
        if cleanup:
            s = s.replace('  ', ' ', 1)
            s = s.replace(' :', ':', 1)
            s = s.replace(' ,', ',', 1)
            s = s.replace(' .', '.', 1)
            s = s.replace(' ?', '?', 1)
            s = s.replace(' !', '!', 1)
            s = re.sub(r'^,+\s', '', s)  # we do not want commas at the beginning of the sentence
            s = re.sub(r'^,+', '', s)    # we do not want commas at the beginning of the sentence
            s = re.sub(r',+$', '', s)    # we do not want commas at the end of the sentence
            s = s.replace(' ', '')
            s = s.lower()
        nfkc.append(s)
    return nfkc

deleted              = to_nfkc(deleted)
deleted_orig         = to_nfkc(deleted_orig, cleanup=False)
deleted_export_readd = to_nfkc(deleted_export_readd)

not_new = []
new = []
for a in deleted:
    if a.startswith('++ '):
        continue

    if not(a in deleted_export_readd):
        new.append(deleted_orig[deleted.index(a)])
    else:
        not_new.append(a)

print('new', len(new))
print('not_new', len(not_new))

deleted.sort()
deleted_export_readd.sort()
save_as('server/data/fr/issue_2259_deleted_MOD.txt', deleted)
save_as('server/data/fr/issue2259_deleted_export_readd_fixed_MOD.txt', deleted_export_readd)

save_as('server/data/fr/issue_2259_added_fixed.txt', not_new)
save_as('server/data/fr/issue_2259_added_push-to-sc.txt', new)
```

**Comment by lissyx** [comment]
@MichaelKohler I'm performing the submission to Sentence Collector.

**Comment by lissyx** [comment]
```
13585 sentences found.

23 sentences were previously submitted.

11382 sentences ready for submission!
```

**Comment by lissyx** [comment]
@MichaelKohler Ping, what's the status here ?

**Comment by MichaelKohler** [comment]
> Let's tackle everything step by step:
> 
>     * Let's wait for a response from the CV team regarding not invalidating already recorded sentences

This is still valid. I've had an initial look, but need to investigate a bit further.. That will be documented in #2259

**Comment by lissyx** [comment]
> > Let's tackle everything step by step:
> > ```
> > * Let's wait for a response from the CV team regarding not invalidating already recorded sentences
> > ```
> 
> This is still valid. I've had an initial look, but need to investigate a bit further.. That will be documented in #2259

Fair enough, I have not kept track of everything here. Hopefully this can be figured out soonish :)

**Comment by MichaelKohler** [comment]
@nukeador can you please merge this after you've merged https://github.com/mozilla/voice-web/pull/2423? Thanks!

**Pull request merged**
