### PR TITLE
[lang:fr] grammar error

### PR DESCRIPTION
**Pull request by drzraf**
By the way, the formulations for this set of sentences is a bit unusual and vague because speaker may like interpret it as a question "are you sure we liked?" rather than "you're sure we liked".
(@ftyers)

### CODE REVIEW

**Comment by drzraf** [comment]
Another possibly confusing one is: "Je suis en train d'écouter. (téléphone)."

**Comment by drzraf** [comment]
That file is **really** of a very bad quality. Grammar, tipo, unknown words, duplicated sentence. WTF?
Can't believe Mozilla (and us the french speakers) could not have been provided with a better set!
@mikehenrty (#1095), why such a set?

**Comment by drzraf** [comment]
Worth noting that any change to a line create a new hash mapping (sha256|b64encode) basically disgarding the work of speakers on the former form the of sentence (!)

**Comment by ftyers** [comment]
Hi @drzraf the sentences come from a collection of parallel sentences in the public domain released by Ofis Publik ar Brezhoneg in Breton and French. The reason we added them was because we had them and they were in public domain. I did not personally check through each of the sentences, but an eyeball glance showed that they looked ok. Personally I expected higher quality, but when you are automatically extracting things there are always likely to be problems with data processing. The most important part was the Breton side of the data, the French part was added as an after thought.

We would be more than happy to make adjustments to the sentences, you are welcome to send a pull request to fix them them. You are also welcome to refer to specific sentences here or in an issue and I will make the edit and pull request. Note that we would like to keep the same order and number of sentences as in the Breton version of the file. This could prove to be a useful dataset for future work on Breton--French speech-to-speech translation.

In addition you are also very welcome to propose your own sentences or collection of sentences. We are always happy to receive more data. In the web interface you may also "skip" a sentence if you do not like it. I expect that this may be used in the future as a method of quality control.

Thank you for your feedback, it has been very helpful.

**Comment by zecakeh** [comment]
@ftyers So from what I got, we're not supposed to remove duplicated sentences from the french version ? After a quick look at the breton version, they also have duplicated sentences, but that would require working on both files at the same time.

I understand the need for sentences to start the project in a language, but I think the validation process should be more thorough.

**Comment by ftyers** [comment]
@zecakeh in an ideal world the sentences would remain aligned. However, given people's strong feelings I don't see much of a problem with removing them. I have the original spreadsheet and can always do a string-for-string lookup to find the translations.

I'd like to apologise to all French contributors for the inadequate proofreading of the sentences before I submitted them. In the future I will endeavour to do a better job.

**Comment by drzraf** [comment]
> Note that we would like to keep the same order and number of sentences as in the Breton version of the file. This could prove to be a useful dataset for future work on Breton--French speech-to-speech translation.

This is a terrible restriction put on both corpus evolution (and particularly the french one), and it's not clear to how maintaining such mapping would be useful.

About dataset preservation when change occurs on the sentence: #1049

About About alternatives corpus, a lot of languages laboratories all around Europe already worked on this for years (usually with a proven methodologies):
* http://wortschatz.uni-leipzig.de/en/download . A couple of sample files to explore:
  * fra_wikipedia_2010_100K-sentences.txt
  * fra_mixed-typical_2012_100K-sentences.txt
* https://deep-sequoia.inria.fr/fr/ (sequoia-8.1/sequoia.surf.conll)
* http://www.atilf.fr/spip.php?article915 (Not available, but could be requested)
* http://www.cnrtl.fr/ probably contains some good ones
Tagging a couple of GH users working with french corpus @prismsoundzero @bsagot @simonmeoni @kimgerdes @gguibon @mmcauliffe

**Comment by mikehenrty** [comment]
Thanks everyone for the great discussion here! A couple of thoughts.

Let's forget about trying to keep translation alignment with the Breton set. It was a good starting point to have both corpora, but at this point I would rather focus on fixing the issues individually than trying to keep the alignment. There are other projects out there for translations, Common Voice is for Speech-to-text data.

Yes, spelling numbers is indeed better than having the numbers listed. It's ok for single digits, but when you get to things like: `2018`, there are several ways to say that. Spelling it out is better, `two-thousand eighteen` or `twenty eighteen`.

Indeed I would love to see more text added to our corpora. But I cannot read French (or most of the languages on Common Voice), so for now we are relying on you the community to flag and address issues. I'm just here to push the merge button when things are ready (and at some point we will give access to other members to do that instead of me). So please continue to have this discussion! And remember, we are all on the same team :) https://github.com/mozilla/voice-web/blob/master/CODE_OF_CONDUCT.md

Please tag me when these fixes are ready to merge. Thanks!

**Comment by lissyx** [comment]
BTW, anyone interested in contribution on french sentences should have a look at https://github.com/mozfr/besogne/wiki/Common-Voice-Fr

**Comment by lissyx** [comment]
@mikehenrty I guess this is now ready to be merged ?

**Pull request merged**
