### PR TITLE
Add Indonesian Accent + sort accent in alphabetical

### PR DESCRIPTION
**Pull request by ariestiyansyah**
Add Indonesian English accent on the list and sort the accent list to alphabetical order

### CODE REVIEW

**Comment by Omniscimus** [comment]
Is English spoken somewhere in Indonesia as a first language? It does not appear [on Wikipedia](https://en.m.wikipedia.org/wiki/Languages_of_Indonesia)... See also #242

**Comment by ariestiyansyah** [comment]
@Omniscimus Sorry, I didn't read that before, well English is not native language here so you can ignore it.

How about the alphabetical order, any comment on that? sometime it's difficult to check dropdown list in unordered style.

**Comment by Omniscimus** [comment]
I like the alphabetical ordering! :smile:

**Comment by ariestiyansyah** [comment]
well, fixed it on cf23e1c

**Comment by mikehenrty** [comment]
Great idea about the Alphabetical ordering! (and yes we are working on better messaging for non-native english speakers), as @Omniscimus  mentioned.

@ariestiyansyah thanks for the contribution. i'm going to accept it, but im going to move `usa` to the top of the list, since that's where a majority of the users are right now.

**Comment by mikehenrty** [comment]
I merge this here: https://github.com/mozilla/voice-web/commit/8ba6c3e28c22d355a695a10821bf038319a9eb80

**Pull request closed without merging**
