### PR TITLE
Update native-names.json

### PR DESCRIPTION
**Pull request by pedlino**
Added Portuguese (Standard, European, from Portugal)

### CODE REVIEW

**Comment by mritunjaygoutam12** [comment]
Oh but I have a question does Português (Brasil) written script is different from Português?
If yes then, @pedlino you have to first add or request these changes [here](https://pontoon.mozilla.org/projects/common-voice/)

**Comment by pedlino** [comment]
Hi Mritunjay Goutam

Some words are different. But the sound is _really_ different (many Brazilian natives have difficulties in understanding the spoken Portuguese from Portugal)
I thought this code referred to the Build Profile interface where Portuguese is also missing form the list of Native Language options.
Where can I fix this?

Thanks!

Pedro
(from Faro, Portugal, Europe)

**Comment by mritunjaygoutam12** [comment]
Hey great.
This project's localization maintained through [Tool](https://pontoon.mozilla.org/projects/common-voice/).

Thank you very much for your contribution.

**Comment by pedlino** [comment]
Thank you for the fast reply. I will look into it.

Cheers!

**Comment by nukeador** [comment]
Please see comment in #1941

**Pull request closed without merging**
