### PR TITLE
german sentences with city names

### PR DESCRIPTION
**Pull request by ubahnverleih**
Created german sentences and filled them with german city names from german cities with population > 50000.

I created these template sentences https://pastebin.com/C90NCgke (updated) and filled them random with names from german cities taken with this [Wikidata Query](https://query.wikidata.org/#SELECT%20%3FitemLabel%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ515.%0A%20%20%3Fitem%20wdt%3AP17%20wd%3AQ183.%0A%20%20%3Fitem%20rdfs%3Alabel%20%3FitemLabel.%0A%20%20%3Fitem%20wdt%3AP1082%20%3Fpopulation.%0A%20%20FILTER%28%28LANG%28%3FitemLabel%29%29%20%3D%20%22de%22%29%0A%20%20FILTER%28%3Fpopulation%20%3E%2050000%29%0A%7D%20group%20by%20%3Fitem%20%3FitemLabel)

With this template and query we could also create this for cities from Austria, Switzerland or international Cities

### CODE REVIEW

**Comment by Djfe** [comment]
Ty for entering these :)
I proofread your template file:
8: brauch*t*
28: *S*ie mi*r*
47: *N*eues
59: zurecht?
86: umst*ei*gen
92: kein()
125: um (optional)

some additional ideas, I got while reading: Flug von nach
Fähre von nach
Schnellzug
Rundfahrten über drei Städte
Kreuzfahrt
nehmt ihr das Schiff nach Grönland etc.

What do you all think about putting this on Pontoon or Crowdin for translation? (since we got a translatable template now)

Regards,
Djfe

**Comment by Djfe** [comment]
Should I proofread the city names, too?
or are there any lines that you added manually (like the last one)
I spotted: Magdeburg while scrolling through ^^

**Comment by ubahnverleih** [comment]
Thank you for checking. Also fixed this errors in this PR. Citynames should be OK, coming from wikidata. Just the last 4 sentences are added manually.
Also updated the template to https://pastebin.com/C90NCgke

**Comment by danielsjf** [comment]
I've tried this on Belgium and got much better results using municipalities than cities. Just in case someone wants to extrapolate this to other countries later on.

**Comment by mikehenrty** [comment]
Thank you @ubahnverleih for the useful sentences, and thank you @Djfe for reveiwing!

@Gregoor are we ready to accept PRs on the new languages?

**Comment by Gregoor** [comment]
Thanks indeed, and we are ready to merge!

**Pull request merged**
