### PR TITLE
[ga-IE] Abair.ie corpus

### PR DESCRIPTION
**Pull request by jimregan**

### CODE REVIEW

**Comment by ftyers** [comment]
The build fail looks like something to do with Travis setup as opposed to something to do with the data itself...

**Comment by jimregan** [comment]
Yeah, that happens. I'd hardly expect text files to have caused a failure :)

**Comment by mikehenrty** [comment]
hi @jimregan , is this ready to go in?

**Comment by jimregan** [comment]
Yes please!

**Comment by mikehenrty** [comment]
thanks @jimregan !

**Pull request merged**
