### PR TITLE
[lang:kab] Create general-newtech1.txt

### PR DESCRIPTION
**Pull request by belkacem77**
Daily expression, some expressions we used on Mozilla kab translation to introduce the new tech language.

### CODE REVIEW

**Comment by belkacem77** [comment]
@Amazigh-bedar @S-Amiri. The corpus we collected on https://github.com/belkacem77/tuddar is also added.

**Comment by mikehenrty** [comment]
@belkacem77, it looks like the corpus here https://github.com/belkacem77/tuddar is licensed under Mozilla Public License 2.0. Any chance you could change that to cc0?

**Comment by belkacem77** [comment]
@mikehenrty no, the corpus is here: https://github.com/belkacem77/tuddar/blob/master/corpus-kab. The sentences are created by @Amazigh-bedar (a daily language). The other sentences I sent are from our translation on Mozilla's Projects (Firefox iOS). We want use also tech language and some kabyle idioms.

**Comment by mikehenrty** [comment]
ah good, i see this license now:
https://github.com/belkacem77/tuddar/blob/master/LICENSE

note, if you wanted to use the official cc0, it looks something like this:
https://github.com/mozilla/voice-web/blob/master/server/data/LICENSE

**Comment by belkacem77** [comment]
I will copy the text (license). I want to make one source and keep the team working on it. It's easier to manage.

**Pull request merged**
