### PR TITLE
Pr/fluentify static

### LINKED ISSUE #843: Fluentify static pages
FAQ, Terms & Privacy

See meta-issue #838 for a description

### PR DESCRIPTION
**Pull request by MekliCZ**
fixes #843 

after consultation with @stasm I have updated fluent-react to 0.6.0 (otherwise, I would not be able to insert HTML to FTL) but kept fluent on 0.4.2; sorry for not making separate PR for this

### CODE REVIEW

**Comment by MekliCZ** [comment]
Looks like I forgot to fluentify FAQ. Don't merge until I'll push FAQ, please :)

**Comment by stasm** [comment]
Nice work, @MekliCZ !

`fluent-react` 0.6.0 removes the possibility of passing elements as $arguments, so you'll also need to fix these two messages in the PR:

https://github.com/mozilla/voice-web/blob/d36ed1117ba8635f89e0fa489cc56a2363d19b3a/web/locales/en/messages.ftl#L12
https://github.com/mozilla/voice-web/blob/d36ed1117ba8635f89e0fa489cc56a2363d19b3a/web/locales/en/messages.ftl#L29

See the [migration notes](https://github.com/projectfluent/fluent.js/blob/master/fluent-react/CHANGELOG.md#dont-pass-elements-as-arguments) for more information about this.

**Comment by MekliCZ** [comment]
Everything fixed, FAQ fluentified, ready to merge. :)

**Comment by Gregoor** [comment]
Thanks you two!
For some reason I get the regeneratorRuntime error (from fluent 0.6.0), even though our package.json specifies 0.4.0. Does it run fine for you @MekliCZ? Might also make a difference whether you use npm or yarn (we're using yarn).

**Comment by MekliCZ** [comment]
@Gregoor I'm using Yarn and this happens sometimes. What resolves it for me is recompilation.

**Comment by Gregoor** [comment]
@stasm I never really published a library, so take this with a grain of salt, but shouldn't `fluent` be a peerDependency of `fluent-react`?

**Comment by stasm** [comment]
It's a [hard dependency](
https://github.com/projectfluent/fluent.js/blob/22da361f77185012d20ca62ec9f5f45e00dd3ddc/fluent-react/package.json#L35) because it exposes [methods for iterating over a sequence of `MessageContexts`](https://github.com/projectfluent/fluent.js/blob/22da361f77185012d20ca62ec9f5f45e00dd3ddc/fluent-react/src/localization.js#L1).

**Comment by Gregoor** [comment]
Ah dang, that makes sense. But then I don't see a way how we can currently use `fluent-react` 0.6.0, as that'll lead us to having `fluent` in there twice with different versions:
```
├─ fluent-react@0.6.0
│  └─ fluent@0.6.0
└─ fluent@0.4.2
```
Unless there's a way for `fluent-react` to use `fluent` 0.4.x when the root application uses is, but I'm way out of my depth here. Not sure if that's possible or makes sense.

Unfortunately I can't get it to not error for me (and also wouldn't like it much if it error'd sth like 50% of the time).

**Comment by stasm** [comment]
I would think `npm` would be capable of re-using `fluent@0.4.2` in this case... Let me see.

**Comment by MekliCZ** [comment]
@Gregoor Dunno why, but I killed the server, started it again and I'm not able to load the react app without regeneratorRuntime. :/

**Comment by stasm** [comment]
I just did the following:

```bash
mkdir tmp && cd tmp
npm i fluent@0.4.x
npm i fluent-react
```

And this is what I see in `npm ls`:

```
/home/stas/tmp
├─┬ fluent-react@0.6.0
│ ├── fluent@0.4.2
│ └─┬ prop-types@15.6.0
│   ├─┬ fbjs@0.8.16
│   │ ├── core-js@1.2.7
│   │ ├─┬ isomorphic-fetch@2.2.1
│   │ │ ├─┬ node-fetch@1.7.3
│   │ │ │ ├─┬ encoding@0.1.12
│   │ │ │ │ └── iconv-lite@0.4.19
│   │ │ │ └── is-stream@1.1.0
│   │ │ └── whatwg-fetch@2.0.3
│   │ ├── loose-envify@1.3.1 deduped
│   │ ├── object-assign@4.1.1 deduped
│   │ ├─┬ promise@7.3.1
│   │ │ └── asap@2.0.6
│   │ ├── setimmediate@1.0.5
│   │ └── ua-parser-js@0.7.17
│   ├─┬ loose-envify@1.3.1
│   │ └── js-tokens@3.0.2
│   └── object-assign@4.1.1
└── UNMET PEER DEPENDENCY react@^0.14.9 || ^15.0.0 || ^16.0.0
```

Did you try `npm install`? It should remove unused packages. Or nuke `node_modules`? :)

**Comment by Gregoor** [comment]
Interesting, thanks for looking into that @stasm! I'll try to figure out why yarn behaves differently there.

**Comment by Gregoor** [comment]
Completely forgot about yarn `resolutions`, which allows us to specify which version a package resolves to (even for dependencies). That fixes it for me!
Unfortunately I can't push to this branch, so could you add this under `devDependencies` in `package.json` and see if it works for you as well @MekliCZ?
```
"resolutions": {
  "fluent": "0.4.2"
}
```

**Comment by MekliCZ** [comment]
Works for me

**Comment by Gregoor** [comment]
Thank you everyone, great work 👍

**Pull request merged**
