### PR TITLE
Adds 500 Russian sentences, fixes #1332.

### LINKED ISSUE #1332: [ru] Create initial dataset of 500 Russian sentences
As discussed [here](https://discourse.mozilla.org/t/russian-speech/18572/20), I would like to push Russian forward.

This is the first issue to provide Russian sentences.

I will work on this in [my fork](https://github.com/highsource/voice-web) and send the PR once I have 500 sentences.

My approach is simply to translate and adapt German sentences I dictate anyway.

Do I have to sign some contributor license?

### PR DESCRIPTION
**Pull request by highsource**

### CODE REVIEW

**Comment by mikehenrty** [comment]
thank you @highsource !

**Comment by mikehenrty** [comment]
have these been reviewed by anyone @highsource ?

**Comment by highsource** [comment]
@mikehenrty No, there was no external review.

**Comment by mikehenrty** [comment]
@highsource do you know anyone who speaks Russian who could do a sanity check (for spelling and grammar)? Doesn't need to be perfect, but we like have a "code review" of sorts for any new sentences coming in.

**Comment by highsource** [comment]
@mikehenrty I have asked my mother to proofread.

**Comment by mikehenrty** [comment]
thank you @highsource !

**Pull request merged**
