### PR TITLE
make cn/hk/tw looks identical in language dropdown list

### LINKED ISSUE #1879: language drop down list - cn/hk/tw looks not identical
The zh-HK (Hong Kong) option look pretty weird within another two, because the "(" is not in good align.

I will open a P/R right later.

### PR DESCRIPTION
**Pull request by irvin**
fix #1879

### CODE REVIEW

**Comment by Gregoor** [comment]
That file is automatically populated from the given language's name for its own locale-code, which can be found on Pontoon: https://pontoon.mozilla.org/zh-HK/common-voice/web/locales/en/messages.ftl/?string=179677

If you update it there, it'll change next time someone runs the `import-locales` script.

**Comment by irvin** [comment]
@gregoor I had send translation suggestion to it but either me or Sammy (our JK liaison) don’t have privilege over zh-HK to approve it.

**Comment by Gregoor** [comment]
I see. Unfortunately I don't know what's the best way to reach out to that community. Maybe @peiying2 can help here?

**Comment by peiying2** [comment]
@irvin @sammyfung, you both are "contributors" to the project. Thus you can only make suggestions, not translations (which doesn't require review and can go directly to staging). I have approved @irvin's suggestion in Pontoon so this should be updated soon.

For the long term, I can give you two translator right only for CV project. Let me know if you prefer to do it this way. Ultimately, Donald is the locale manager. Let me know what you prefer.

**Comment by irvin** [comment]
Hi @peiying2 , I don't need that (we have @petercpg as our zh-TW locale owner) so I think just gain @sammyfung for zh-HK is fine.

**Comment by peiying2** [comment]
I have added Sammy as a translator to zh-HK. This way he can approve your suggestion.

**Comment by Gregoor** [comment]
Great, thanks for helping Peiying! I'll close this PR then, as it'll be fixed through Pontoon.

**Pull request closed without merging**
