### PR TITLE
Moving pt-BR into pt

### PR DESCRIPTION
**Pull request by nukeador**

### CODE REVIEW

**Comment by nukeador** [comment]
There are some translated names into the localization file and I suspect we'll need to change in English from "Portuguese (Brazil)" → "Portuguese"

**Comment by Gregoor** [comment]
yup, and we need to change things in the DB. And we'd need to change the locale code used in the messages file, as we're not supposed to edit them through anything but Pontoon. Also unless we change the identifier of "Portuguese (Brazil)", other language communities won't know that the string changed.

**Comment by peiying2** [comment]
I forgot to mention, in Pontoon, we have pt-BR because we have no pt in Pontoon. Will this change call problems between github and Pontoon? I just realize this change is different from the example  I gave you on "bn" locale merge.

**Comment by nukeador** [comment]
@peiying2 From your previous messages I assumed you will create a pt locale for Common Voice once we apply these changes into our folders.

**Comment by peiying2** [comment]
I have set up `pt` locale in Pontoon. You can move anytime you want. Once this is done, let me know right away. We will migrate the metadata to pt so we preserve all the contribution histories.

**Comment by nukeador** [comment]
@Gregoor I've merged changes that happened in the pt-BR localization over master in the past hours to fix the conflict. We would need to merge this into master and then after Peiying updates pontoon we can run yarn update-locales to get the new info and avoid pt-BR coming back to our list.

**Comment by nukeador** [comment]
@peiying2 it's been difficult to merge this since every day pr-BR has been committing changes to the repo. Is there a way to block new contributions to pt-BR on pontoon while we merge this?

**Comment by peiying2** [comment]
I have made pt-BR locale as a read-only locale for now until we complete the data migration. Then it will be permanently removed from the CV project.

**Comment by peiying2** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1571039 - the change in Pontoon side takes a bit more work. I guess this is the first time for Portuguese and some code change needs to happen before data migration. This will be taken care of next week. If the communities have any issues, we can tell them this is taking place and will be resolved soon.

**Comment by peiying2** [comment]
On Pontoon, the megadata migration from pt-BR to pt is complete.

**Pull request merged**
