### PR TITLE
create corpus-hocine8.txt

### PR DESCRIPTION
**Pull request by belkacem77**
300 more Sentence from. corpus16,corpus17,corpus18
source: https://github.com/Hociben/corpus-kabyle
Origine Licence CC0

### CODE REVIEW

**Comment by Hociben** [comment]
@belkacem77 thanks

**Comment by belkacem77** [comment]
@Gregoor I got more sentences. Please merge them.

**Comment by Hociben** [comment]
@belkacem77 ok

**Comment by Hociben** [comment]
@belkacem77 ok

**Comment by belkacem77** [comment]
Hi @Gregoor . Please would you like merge these sentences?

**Comment by belkacem77** [comment]
@Gregoor sorry I didn't noticed your comment.

Please, yes you can merge them

**Pull request merged**
