### PR TITLE
fix(button icon disappear on hover)

### LINKED ISSUE #2655: Button Icon Disappear on hover
## Description
Button Icon Disappear on hovering

## Current Behaviour
Icon is white and the background is also white, that's why the button disappear

## Expected Behaviour 
Icon color should also change with the text, and will be visible when hovering the button

## Related Image
Normal Button
Screenshot from 2020-03-28 15-59-32

Hover button
Screenshot from 2020-03-28 15-59-36

## Additional Information
I would like to work on it

### PR DESCRIPTION
**Pull request by shakti97**
Fixes #2655 

After fix
Screenshot from 2020-04-05 18-33-39

### CODE REVIEW

**Comment by phirework** [comment]
This hardcodes a colour value to the cloud icon, which affects everywhere it's used, not just the Dataset download page, and also makes it less flexible to work with in the future. Please use CSS `:hover` instead.

**Comment by shakti97** [comment]
Thanks for the review , will do the recommended changes and update you :)

**Comment by shakti97** [comment]
Added the recommended changes , can you please review again and suggest changes :)

**Comment by phirework** [comment]
Thanks for making the changes!

**Pull request merged**
