### PR TITLE
Normalize audio for verification

### LINKED ISSUE #336: Adjust volume automatically when listening to multiple recordings
Many music players can do this, why not use it here too?

Just adjust the audio pitch when hearing to sentences. I always have to adjust the volume up and down and by using such an automatically adjustment I could prevent this.

### PR DESCRIPTION
**Pull request by est31**
Implement audio normalization on the client, using a method based on ReplayGain.

Fixes #336

### CODE REVIEW

**Comment by est31** [comment]
@Gregoor please take a look.

I've tested the changes locally. They do work.

**Comment by est31** [comment]
How can Travis CI be fixed?

**Comment by est31** [comment]
Caniuse [says](https://caniuse.com/#search=webaudio) that all of the [supported browsers](https://github.com/mozilla/voice-web/blob/master/docs/browser-support.md) should have WebAudio.

**Comment by est31** [comment]
Also note that this needs [changes in the S3 bucket configuration](https://docs.aws.amazon.com/en_us/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors) to enable CORS requests from voice.mozilla.org.

**Comment by Gregoor** [comment]
I'm getting CORS warnings when trying it out, we might have to add CORS headers allowing the AWS domains.
Another thing that came to mind is that we would also want to use this for the listen widget on the homepage as about 40% of all listens still happen there.

**Comment by est31** [comment]
@Gregoor the CORS settings need to be adjusted in the Bucket, not on the side of the website. See the page I've linked above. As for the listen widget, sure will do.

**Comment by Gregoor** [comment]
Oh, pardon read over that. Thanks for the pointer!

**Comment by Gregoor** [comment]
Works great for me locally! Thanks for also bringing it to the old widget. I'm awaiting the config change of the staging/production buckets and then I'll merge it!

**Comment by est31** [comment]
Rebased, as #1337 caused conflicts.

**Comment by Gregoor** [comment]
Thanks for keeping it synced! I was told the infra change is next up on the list of todos, I hope that means soon 🙃

**Comment by lissyx** [comment]
@est31 @Gregoor When can we have that live? It would be such an awesome improvement!

**Comment by Gregoor** [comment]
Thanks for the reminder. Full plate this week 🙈 Let's take this live!

**Comment by Gregoor** [comment]
@est31 I reverted this for now (eedf104347c80bc6fbe86b51f298fe290d054f13), as it broke Safari (#1463) and I couldn't figure out how to unbreak it. What I found out: 
Safari doesn't properly implement decodeAudioData / or doesn't implement the new Promise based version of it. But even when I used the old callback syntax, it wouldn't work.

**Comment by est31** [comment]
Oh sorry to hear that it broke Mac OS. I don't have an apple device so can't be of much help, but I've found [this](https://github.com/mohayonao/promise-decode-audio-data) library. @Gregoor could you maybe try whether using it fixes the issue?

**Pull request merged**
