### PR TITLE
Fixed the bug for Issue #259.

### PR DESCRIPTION
**Pull request by ayushbansal07**
In the reset() function, previously we fetched newSentences first and reset the recordings afetr that.
Now I just interchanged the order.

### CODE REVIEW

**Comment by mbebenita** [comment]
I'm not sure how things work in Preact, but in React setting the state is an asynchronous operation and there's no guarantee that the new state will be available right after the call to `setState`.

**Comment by ayushbansal07** [comment]
I too am not sure whether setState would be synchronous or asynchronous.  Though, when I tested the app on my local machine it worked fine. 
The main problem here was that when we fetched the new sentences by calling the function newSentenceSet(), the value of recordedSentenceCount remains 3 since the recordings do not get reset. So, the necessary part was just to reset recordings.

**Comment by mikehenrty** [comment]
Yeah, @mbebenita is right, setState is asynchronous function, so even if this fixes the problem locally, the solution would be non-deterministic. Sounds like the problem is be around recordedSentenceCount not getting reset with the sentences? Is there a way we can make those align?

**Comment by ayushbansal07** [comment]
Would initialising state.recordings to empty array before calling the newSentenceSet() function work?

**Comment by mikehenrty** [comment]
> Would initialising state.recordings to empty array before calling the newSentenceSet() function work?

Unfortunately, you are not allowed to set the object state directly, you must use setState to take advantage of all the react rendering magic.

That said, I think you are on the right track with your change here. It makes sense to setState first (even if it is asynchronous). Part 2 is, we need to simplify the `newSentenceSet` function. The logic we have there now was from a fix (https://github.com/mozilla/voice-web/commit/0a5c9dab7788f09ef401c1cd72c3fe560cb73746) to an outdated bug. If, in addition to the changes you have made here, you also make the `newSentenceSet` function always fetch 3 sentences, I think this will fix this for good. Perhaps something like this:
``` 
newSentenceSet() {
    this.api.getRandomSentences(SET_COUNT).then(sentences => {
      this.setState({ sentences: sentences.split('\n') });
    });
}
```

Can you give that a try @ayushbansal07 ?

**Comment by ayushbansal07** [comment]
@mikehenrty , I did and tested the change so that the function newSentenceSet always fetches 3 ( = SET_COUNT) sentences. Everything was working fine locally.

**Comment by mikehenrty** [comment]
Great! I squashed your commit, and merge this here: https://github.com/mozilla/voice-web/commit/c3ac34db783194bffa1980f0444d2666286d19b1

**Pull request closed without merging**
