### PR TITLE
German Europarl corpus v7

### PR DESCRIPTION
**Pull request by stefangrotz**
This pull request contains around 379 000 sentences from the Europarl Corpus from debates in the european parliament: http://www.statmt.org/europarl/

The file contains sentences
- with no more than 14 words
- no double upercase letters (like UN or EU)
- no single letters followed by a full stop
- no lines that doesn't end with . ? or !
- no numbers, (sqare) brakes,...
- I deleted all kind of foreign letters and alphabets 

As discussed in the last pull request #2487 the QA process is this time a sheet where we review 4000 random sentences from the corpus:

https://docs.google.com/spreadsheets/d/1V7dqkmXBTGK07pW8qzdYAKnUKWN8iXLW7MKfru66sw0/edit#gid=0

2000 Sentences are already reviewed and it looks like the end result will be under 5% error rate. Based on the reviews I also removed sentences with slashes from the file in this commit. 

I created this pull request to be ready once the review is done and to motivate us reviewers a little.

### CODE REVIEW

**Comment by benekuehn** [comment]
@stefangrotz can be pulled now. I reviewed the remaining 2000 sentences.

**Comment by stefangrotz** [comment]
Hey @nukeador the 4000 sentences are reviewed. 94.25% are fine, 2.10% have spelling errors, most of them are caused by the german spelling reform that happened in 1996. Another 3.05% are hard to pronounce, mainly names and political words. 

IMO this can be merged.

**Comment by nukeador** [comment]
Can you link the document with the QA analysis and the names of the reviewers? 

Also, can you clarify if the total number of sentences are 389615 or if this is just a portion of what can be extracted?

Thanks!

**Comment by stefangrotz** [comment]
Good question. The original corpus is very big, 328 mb, but the sentences with more than 14 words are alone 296,4 mb.  Such an extreme decline after filtering only the length most likely only happens with sentences from german politicians oO 

The rest is filtered in the way I described it above.

**Comment by nukeador** [comment]
Is there a way to use sentences longer than 14 words, splitting them somehow they make sense?

@MichaelKohler do you remember who we did for wikipedia?

**Comment by MichaelKohler** [comment]
> @MichaelKohler do you remember who we did for wikipedia?

For the Wikipedia script we just discard anything that is longer than specified in the rules.

**Comment by stefangrotz** [comment]
I also don't think that this is doable without a lot of manual work.

**Comment by nukeador** [comment]
Great, before accepting this PR, I'm going to check with Alex and Rosana so they can review.

**Comment by stefangrotz** [comment]
Hey @nukeador any news here?

**Comment by nukeador** [comment]
We have been away last week for Berlin all hands, we'll loop this into our next meeting. I can't commit to a timeline because we'll probably need to ask for legal approval before merge this.

**Comment by stefangrotz** [comment]
I see, thanks for the update. The legal explanation of the dataset is indeed very vague "We are not aware of any copyright restrictions of the material." 

> we'll probably need to ask for legal approval before merge this.
You just merged it, was this a mistake?

**Comment by stefangrotz** [comment]
Thanks for the update. The information about the legal status of this dataset is indeed a little vague.

> We are not aware of any copyright restrictions of the material.

**Comment by stefangrotz** [comment]
I asked the [Citizens' Enquiries Unit (Ask EP)](https://www.europarl.europa.eu/atyourservice/en/askEP.html) about the licence of this corpus, I hope this will clear things up.

**Comment by nukeador** [comment]
I got positive signs from legal this week, I'm just waiting for a few answers more before merging this.

**Comment by MichaelKohler** [comment]
@nukeador any update here?

**Comment by nukeador** [comment]
We should be fine. I'm working with @phirework to define where to add attribution for this sentences.

**Comment by phirework** [comment]
Thanks for your patience everyone! This is all sorted :)

**Comment by CennoxX** [comment]
Just came across this, there are still some structural problems with the text, some for hundreds of sentences.
For example:
* leading spaces
* there are still sentences that don't end with . ? or !
* small case then uppercase inside one word > often an mistake
  * pKopf/pLand/... instead of "pro Kopf", "pro Land"
  * sentences with "Beifall", "Berichterstatter", "Berichterstatterin", "Mitglied der Kommission", "Verfasser, "Herr Präsident!" added before (with or without space)
* old German, for example "muß", "gewiß", "Schluß", ...

How should these be solved? Pull Request?

**Comment by stefangrotz** [comment]
Hello @CennoxX 

> leading spaces
This should indeed be fixed.

> there are still sentences that don't end with . ? or !
Really? could you give an example?  I used `awk '/\./ || /\?/ || /\!/'` Do delete all lines without sentence signs.

> lowercase then uppercase inside one word > often an mistake 
and 
> old German, for example "muß", "gewiß", "Schluß", ..

[In our review](https://docs.google.com/spreadsheets/d/1V7dqkmXBTGK07pW8qzdYAKnUKWN8iXLW7MKfru66sw0/edit#gid=0)  the error rate was below 6 % so decided to accept things like this . But we can always delete wrong sentences afterwards.

I searched for tools to fix errors resolving from the spelling reform of 1996, but I found nothing.

**Comment by MichaelKohler** [comment]
just a quick comment from my side: sentences without ending punctuation is fine for now

**Comment by CennoxX** [comment]
>  Do you have a quick idea how to fix this?

The sentences could be corrected with regex/some manual search and replace. The awk regex for sentence signs should end with `$` otherwise it only searches, if it contains one or more sentence signs at any position. Even if the error rate is below 6 %, before importing the sentences, it's relatively easy to correct recurring mistakes (replace "muß with muss" etc.) or search for "ß" and correct if necessary. Can I prepare another Pull Request with the changes?

**Comment by benekuehn** [comment]
Ill have a look into old spelling now.

**Comment by stefangrotz** [comment]
>  Can I prepare another Pull Request with the changes?

That would be great.

**Comment by benekuehn** [comment]
Created a new pull request with my changes here: https://github.com/mozilla/voice-web/pull/2610
I caught all muß and most of the other common ß to ss. I looked through the first 2000 ß to caught most of them. Hopefully havent missed that much.

**Pull request merged**
