### PR TITLE
Update sentence contribution instructions

### PR DESCRIPTION
**Pull request by davidak**
This update should make the current situation more clear in this document.

Feel free to change wording when you can improve it!

### CODE REVIEW

**Comment by davidak** [comment]
@DNGros thanks.
I accepted the suggestion, which created a new commit.
To have only one, squash and merge the PR!

**Comment by Gregoor** [comment]
@nukeador any other info you think might be valuable to add to this?

**Comment by nukeador** [comment]
I think that topic is a good place, I'm working with both community and deep speech team to have a proper documentation on the guidelines for sentence collection that will be incorporated into the tool.

**Comment by nukeador** [comment]
Let's close this one since we already launched the sentence collector.

**Pull request closed without merging**
