### PR TITLE
Create bretonSentences001.txt

### PR DESCRIPTION
**Pull request by DiaouligRuz**
New Breton sentences.

### CODE REVIEW

**Comment by DewiBrynJones** [comment]
Helo @DiaouligRuz ! 

Can you provide some background as to where these sentences come from?

Trugarez
Dewi

**Comment by DewiBrynJones** [comment]
Perhaps @tornoz and/or @Wanibzh29 would be best qualified to look at these sentences also.
Trugarez

**Comment by DiaouligRuz** [comment]
Hi @DewiBrynJones !

I came up with these sentences myself, in a moment of plentiful inspiration ;) I did my best to comply with the guidelines provided by @mikehenrty here: https://github.com/mozilla/voice-web/issues/341#issue-244926070.

Trugarez dit ivez.

**Comment by DewiBrynJones** [comment]
That's great! 

#341 mentions that Michael would read each one (English sentence ;) ) etc. I think it would be great for another Bretagne speaker to proofread your sentences - perhaps @tornoz and/or @Wanibzh29? 

It would be great also if there was a group or community of Bretagne speakers to progress CommonVoice Brezhoneg in general.

Trugarez!

**Comment by tornoz** [comment]
Great job!

A little feedback:

l54. E Douarnenez e c'hoarz*h*er bemdez.
l64: Bremañ eo re *z*iwezhat [...]

**Comment by Wanibzh29** [comment]
Hi everyone,
Good job :)
I have seen a very few mistakes, and some sentences could have some different version.
l4. Instead of Bro Alamagn -> Bro-Alamagn.
l17. "partoud" -> partout.
l21. Tad kozh -> Tad-kozh.
l26. There is a different version of it if you want to add it: To pa ri ti, pa ri ti to po.
l32. perka -> perak.
l59. Ne fell ket din ken mont d'ar skol. Could also be: "Ne fell ket din mont d'ar skol ken".
l62. Velajenn -> vilajenn no?
l66.  Ne vez ket kavet kalz a levrioù ken er stal. Could also be:  Ne vez ket kavet kalz a levrioù er stal ken.
That's all for me :)

**Comment by DiaouligRuz** [comment]
Hi @tornoz and @Wanibzh29,
Thanks a lot for proofreading the sentences. I have now updated the file.

**Comment by Wanibzh29** [comment]
Hello,
Is the Breton tatoeba sentence corpus re-used by Common Voice ? @Tornoz and I have translated a lot of sentences on this website, they are almost 10 thousands on it, it is a quite important corpus for Breton.
If you want @DiaouligRuz  you can on the tatoeba website for translating sentences.

**Comment by DewiBrynJones** [comment]
I'll make enquiries about Tatoeba and what steps (if any) @tornoz @Wanibzh29 should take to import their Bretagne sentences into CommonVoice.

@DiaouligRuz has corrected his sentences. I don't have the authority to merge into CommonVoice, but I think everyone is happy and that someone in Mozilla can go ahead. In the meantime, it'd be great if @DiaouligRuz joined with @tornoz and @Wanibzh29. 

Trugarez!
Hwyl!

**Comment by DiaouligRuz** [comment]
I would indeed be happy to contribute more ;)

**Comment by Gregoor** [comment]
Thanks for your efforts! We're about to launch a beta of our sentence collection tool, please submit your sentences through that once it's ready. It'll be announced in our Discourse very soon:
https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530/

**Pull request closed without merging**
