### PR TITLE
Add more Thai sentence

### PR DESCRIPTION
**Pull request by wannaphongcom**
Add more Thai sentence.

### CODE REVIEW

**Comment by veer66** [comment]
I read all of them and they are okay.

**Comment by wannaphongcom** [comment]
@Gregoor please merge this commit.

**Comment by pureexe** [comment]
Is it ok to have broken Thai word "มั้ย"? Should it change to "ไหม" instead?

https://github.com/mozilla/voice-web/blob/9034ebcd4dea8fa59f840da3c636fc972a53baa9/server/data/th/Wannaphong.txt#L38

**Comment by wannaphongcom** [comment]
@pureexe  Thank you.

**Pull request merged**
