### PR TITLE
sentences from Haval organisation

### PR DESCRIPTION
**Pull request by ftyers**
Here are some more sentences sourced by the organisation "Haval".

### CODE REVIEW

**Comment by mirontoli** [comment]
Good work, @ftyers

**Comment by Gregoor** [comment]
Thanks for your efforts! We're about to launch a beta of our sentence collection tool, which will allow community-review of sentences and through which we'll able to verify some hard-requirements. Please submit your sentence through that once it's ready. It'll be announced in our Discourse very soon:
https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530/

**Comment by ftyers** [comment]
@Gregoor I've uploaded them to the corpus creator site here: https://common-voice.github.io/sentence-collector/#/add

How long will it take for them to be added? Do we need to go through and review them all again manually?

**Comment by ftyers** [comment]
Can we get this PR merged in the meanwhile? @Gregoor 

@nukeador I've submitted a couple of issues to GitHub.

**Comment by nukeador** [comment]
It's going to be just a few days, thanks for your petience.

**Comment by ftyers** [comment]
@nukeador the PR has been waiting a month, and we have community members who have read out all of the existing sentences and are waiting to be able to read out more. This really effects engagement.

**Comment by nukeador** [comment]
I understand this could be frustrating but having sentences deeply reviewed is important to ensure they are useful for the Deep Speech algorithms, we don't want to lower the bar and having the risk of accepting sentences that will turn useless (wasting more people's time).

Unfortunately we don't have a process to get that and at the same time avoid other people mass approving sentences with no review.

Let me know if you want to expand this conversation over slack or other sync channel.

**Comment by ftyers** [comment]
@nukeador they have been "deeply reviewed". I'm happy to discuss it on IRC: `#machinelearning`.

**Comment by nukeador** [comment]
Hi,

I've had a conversation with @ftyers about this.

- We made sure all sentences were OK according to the sentence collection validation.
- We understand that the community review was done before we announced the changes in the process to submit new sentences.

For that reason we are going to accept this PR in this case. Moving forward and once we launch the beta version of the tool, sentences will have to be submitted and reviewed there in order to be validated.

Cheers.

**Comment by ftyers** [comment]
@nukeador and @Gregoor thanks!!!  :)

**Pull request merged**
