### PR TITLE
hide input feild

### PR DESCRIPTION
**Pull request by mritunjayz**

### CODE REVIEW

**Comment by mritunjayz** [comment]
This can be merged !

**Comment by mritunjayz** [comment]
@Gregoor

**Comment by Gregoor** [comment]
Won't the input stop being clickable if we hide it? I.e. can one still upload an avatar?

**Comment by mritunjayz** [comment]
Yes, It works only hide the default HTML input box. Otherwise, everything will be the same.

**Comment by Gregoor** [comment]
Awesome, thanks!

**Pull request merged**
