### PR TITLE
disable scroll

### PR DESCRIPTION
**Pull request by mikehenrty**
This is a potential fix for #33.

### CODE REVIEW

**Comment by mikehenrty** [comment]
@mbebenita can you take a look at this?

**Comment by mbebenita** [comment]
Ohh, I just submitted something that does the same thing. But I didn't set the bounces option.

**Comment by mikehenrty** [comment]
Fixed in 85f0aad4911cb06d70c2b1be7f10f3c01bd57d23

**Comment by mikehenrty** [comment]
@mbebenita How is it with bounces still on? Does it look right now?

**Pull request closed without merging**
